### ISSUE TITLE
[Bug]: Unable to install the IRSA prepare step

### ISSUE THREAD

**Issue by arunposh** [aws-samples/eks-workshop-v2#1004]
### Installation method

Workshop Studio

### What happened?

While run the irsa prepare step getting error . Tried multiple times but no luck 

### What did you expect to happen?

Irsa prepare steps should be installed without any issues 

### How can we reproduce it?

 prepare-environment security/irsa    - Run this command and getting the error . 

Its not for everyone . As per instructor no workaround as of now . 

### Anything else we need to know?

 prepare-environment security/irsa                                                                                                                                            
Refreshing copy of workshop repository from GitHub...

Resetting the environment...
Tip: Read the rest of the lab introduction while you wait!
Cleaning up cluster access entries...
An error occurred, please contact your workshop proctor or raise an issue at https://github.com/aws-samples/eks-workshop-v2/issues
The full log can be found here: /eks-workshop/logs/action-1720478765.log
WSParticipantRole:~/environment $ tail -100 

### EKS version

 kubectl version
Client Version: v1.29.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b

{"Version":"0.180.0","PreReleaseID":"","Metadata":{"BuildDate":"2024-05-29T19:54:28Z","GitCommit":"7630270"},"EKSServerSupportedVersions":["1.23","1.24","1.25","1.26","1.27","1.28","1.29","1.30"]}

**Comment by ROunofF** [comment]
I'm sorry you ran into an issue with the prepare-environment here. Unfortunately we are missing the log line that could help us in that tail -100 command or the ability to look at the your cluster state to understand what went wrong.

**Comment by arunposh** [comment]
Hi @ROunofF  , 
  Thats the only logs available in the log file . Unfortunately i didn't get any additional debug logs .

**Comment by niallthomson** [comment]
@arunposh if you still have access to that Cloud9 the file mentioned in the error output should still be there. Please attach it here.

**Comment by niallthomson** [comment]
I was able to get access to an account where this was happening in real-time and resolve the issue.
