### ISSUE TITLE
[Bug]: The fsx for Netapp ONTAP portion of the lab cannot be completed due to  the CSI driver returning a 400 response code.

### ISSUE THREAD

**Issue by GH-JeffJ** [aws-samples/eks-workshop-v2#1019]
### Installation method

Own AWS account

### What happened?

When deploying the fsx components, the CSI driver fails to provision. Attempting to manually deploy the driver using the newer version fails as well. The newer version is flagged as requiring a subscription in the marketplace so I suspect the licensing for the driver has changes?

### What did you expect to happen?

The expected behavior is that the fsx for netapp driver will deploy

### How can we reproduce it?

prepare the environment, after about 15 minutes when the fsx resources come online, you will receive the error. Snippets from the main.tf config and the error are attached:

main.tf
resource "aws_eks_addon" "fsxn_csi_addon" {
  cluster_name  = var.addon_context.eks_cluster_id
  addon_name    = "netapp_trident-operator"
  addon_version = "v23.10.0-eksbuild.1"
  
Error
Error: creating EKS Add-On (eks-workshop:netapp_trident-operator): operation error EKS: CreateAddon, https response error StatusCode: 400, RequestID: d9bd4e72-03f1-4969-b806-d3fca45a63bd, InvalidParameterException: Addon version specified is not supported
│ 
│   with module.lab.aws_eks_addon.fsxn_csi_addon,
│   on lab/main.tf line 1, in resource "aws_eks_addon" "fsxn_csi_addon":
│    1: resource "aws_eks_addon" "fsxn_csi_addon" {

### EKS version

1.29

**Comment by niallthomson** [comment]
@GH-JeffJ apologies, this lab has been removed from the latest release of the workshop due to issues.
