### ISSUE TITLE
Update in Cloudformation using Cloud9

### ISSUE THREAD

**Issue by peachycloudsecurity** [aws-samples/eks-workshop-v2#1021]
### What would you like to be added?

Any other ide instead of Cloud9 IDE, maybe vscode on ec2 via terraform

### Why is this needed?

As we can see Cloud9 stopped being available to new accounts ([link](https://dev.classmethod.jp/articles/aws-start-to-restrict-codecommit-and-cloudsearch/). Cloudformation relies on cloud9 for this lab

Reference: https://github.com/SummitRoute/aws_breaking_changes

**Comment by niallthomson** [comment]
Hi @peachycloudsecurity this work is already underway, we'll provide an update soon.

**Comment by niallthomson** [comment]
We are aiming to have this completed by the end of August due to a significant amount of work required to adjust various aspects of the workshop to a new operating model.

**Comment by kirazero17** [comment]
How about using local VSCode to connect to AWS ? I'm still testing with the modified path on WSL1 at the moment.
![image](https://github.com/user-attachments/assets/52990190-0f45-4d1a-9dea-743d1ae2486c)
It can create the environments now.

**Comment by peachycloudsecurity** [comment]
I have also created [vscode-eks](https://github.com/kubernetesvillage/vscode-eks) terraform code using the existing workshop script and Coder code-server. 
Additionally, I have explored AWS Shell, which is promoted at [cloud9 page](https://aws.amazon.com/cloud9). However, these alternatives require ongoing maintenance and may present challenges for new users compared to the previous Cloud9 lab deployed via CloudFormation.

**Comment by jvdadda** [comment]
Thanks @niallthomson, I see that you have made some modification to have VSCode support, have you an ETA for release of it ?

**Comment by niallthomson** [comment]
The release that was just published adds an option that uses VSCode (via code-server) which should be considered "preview". We'd love to hear feedback on any issues you find.

**Comment by niallthomson** [comment]
I'm going to close this. Please open relay any problems you encounter via a new GitHub issue.
