### ISSUE TITLE
[Bug]: While getting started in own account, VSCode or Cloud9 instance setup Cloudformation is throwing error

### ISSUE THREAD

**Issue by bhoslelalit** [aws-samples/eks-workshop-v2#1144]
### Installation method

Own AWS account

### What happened?

I get following error while doing the setup in own AWS account, i have tried this in 2 regions ap-southeast-1 and us-west-2:

[ERROR] TypeError: '>=' not supported between instances of 'WaiterError' and 'int'
Traceback (most recent call last):
  File "/var/task/index.py", line 56, in lambda_handler
    responseData = {'Error': traceback.format_exc(e)}
  File "/var/lang/lib/python3.12/traceback.py", line 184, in format_exc
    return "".join(format_exception(sys.exception(), limit=limit, chain=chain))
  File "/var/lang/lib/python3.12/traceback.py", line 139, in format_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
  File "/var/lang/lib/python3.12/traceback.py", line 733, in __init__
    self.stack = StackSummary._extract_from_extended_frame_gen(
  File "/var/lang/lib/python3.12/traceback.py", line 411, in _extract_from_extended_frame_gen
    if limit >= 0:

### What did you expect to happen?

expected outcome: vscode or cloud9 interface to be setup correctly

### How can we reproduce it?

Run cloud9 or vscode setup link in your account: https://www.eksworkshop.com/docs/introduction/setup/your-account/

### EKS version

NA

**Comment by bhoslelalit** [comment]
was able to make this work in ap-southeast-1 by removing additional quote(") in parameter RepositoryRef changed from stable" to stable

**Comment by niallthomson** [comment]
Thanks for the report! This was fixed by #1157 that will release today.
