### ISSUE TITLE
Typo in 2 labs

### ISSUE THREAD

**Issue by scouturier** [aws-samples/eks-workshop-v2#202]
## What would you like to be added/changed?

https://reinvent.eksworkshop.com/docs/fundamentals/managed-node-groups/taints/configuring-taints - "Challange" -> "Challenge:

https://reinvent.eksworkshop.com/docs/observability/resource-view/extensions/webhook-configurations - "WebhookConfigurations" -> "Webhook Configurations"

**Comment by svennam92** [comment]
resolved in the latest iteration
