### ISSUE TITLE
Configuring taints lab last command outputs a lot of data, we should add grep at the end to output only what's required for simplicity

### ISSUE THREAD

**Issue by scouturier** [aws-samples/eks-workshop-v2#207]
## What would you like to be added/changed?

Configuring taints lab last command outputs a lot of data, we should add grep at the end to output only what's required for simplicity

**Comment by svennam92** [comment]
appears to be resolved in the latest iteration of the workshop
https://www.eksworkshop.com/docs/fundamentals/managed-node-groups/taints/configuring-taints/
