### ISSUE TITLE
Terraform 1.3.0 compatibility

### ISSUE THREAD

**Issue by niallthomson** [aws-samples/eks-workshop-v2#215]
## What would you like to be added/changed?

Currently we pin the Terraform version 1.2.9 and explicitly do not allow anything higher. This was originally due to EKS Blueprints issues with TF 1.3.0. Now that this is resolved upstream we should support 1.3.0.

Initial testing shows that this version has changed how module outputs are handled during `destroy`, and using 1.3.0 seems to give an error.

Tasks for this issue:
- [ ] Make any Terraform changes necessary for compatibility
- [ ] Relax provider requirement
- [ ] Update version pins for GitHub Actions and CFN CodeBuild to the latest 1.3.X version

**Comment by svennam92** [comment]
Addressed with https://github.com/aws-samples/eks-workshop-v2/pull/286
