### ISSUE TITLE
Network Policies

### ISSUE THREAD

**Issue by niallthomson** [aws-samples/eks-workshop-v2#228]
## What would you like to be added/changed?

Lab demonstrating how to use Kubernetes Network Policies to restrict traffic in the EKS cluster. Install Cilium in the cluster with Blueprints addon https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/modules/kubernetes-addons/cilium

Suggested flow:
1. Describe how Cilium is installed
2. How that all Pods can communicate to each other (exec in to catalog and curl checkout?)
3. Implement deny all rule and show that website is now broken
4. Add policies to all allow communication required
5. Demonstrate that Pods cannot all communicate to each other (replicate step 2)

**Comment by huytn1219** [comment]
@niallthomson I can work on this!

**Comment by huytn1219** [comment]
@niallthomson can you assign this feat to me? tks

**Comment by niallthomson** [comment]
Resolved by #674
