### ISSUE TITLE
Module on How to debug k8s 

### ISSUE THREAD

**Issue by mkraenz** [aws-samples/eks-workshop-v2#292]
### What would you like to be added?

a module how to debug a broken kubernetes system for common issues. For example, why is my pod not being exposed. Or why is my database crashlooping (say, the volume is full). 

Justin Garrison shared this with me on the AWS Twitch Stream (2023-02-08). Might be a good starting point
https://thenewstack.io/living-with-kubernetes-12-commands-to-debug-your-workloads/

### Why is this needed?

It's needed because in the real world things WILL go wrong at some point. There might be a multitude of reasons why it goes wrong and a very important part of being a developer/devops engineer is figuring out what's wrong, and eventually finding a proper solution.

**Comment by svennam92** [comment]
Thanks for opening this issue @mkraenz. While we initially considered including Kubernetes basics content, one of our core tenets is to keep the content Amazon EKS-focused. That being said, we do link heavily to Kubernetes and other open-source documentation. We have no plans at the moment to include a dedicated module for debugging Kubernetes. 

I'd be open to a PR with links to debugging resources such as this.
