### ISSUE TITLE
[Bug]: Time out waiting for condition in resource "helm_release" "addon"

### ISSUE THREAD

**Issue by bghis** [aws-samples/eks-workshop-v2#293]
### What happened?

Run terraform init | apply. Getting the following error: 

Error: timed out waiting for the condition
│
│   with module.cluster.module.ec2.helm_release.addon[0],
│   on .terraform\modules\cluster.ec2\modules\kubernetes-addons\helm-addon\main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {

It seems to be related to a package and not the code itself. Maybe some packages/dependencies are broken upstream.

### What did you expect to happen?

Not get any error during Terraform apply. Be able to see addons in EKS cluster.

### How can we reproduce it?

Follow the steps in this article: https://www.eksworkshop.com/docs/introduction/setup/your-account

### EKSversion

Kubernetes version: 1.23 |  platform version: eks.5

![2023-02-08 20_42_13-eks tf - eks-workshop-v2 - Visual Studio Code](https://user-images.githubusercontent.com/55256429/217719756-c59f8fa5-ef77-49a8-97cc-904ca46d4e3b.png)

**Comment by bghis** [comment]
May be related to OS you are running Terraform from. Ran from a Ubuntu and terraform apply works as expected.

**Comment by darshcloud** [comment]
I am currently facing the same issue on windows machine. How can i fix this while running on windows machine?
