### ISSUE TITLE
[Bug]: When terraform apply fails at certain points, destroy will fail too.

### ISSUE THREAD

**Issue by digihunch** [aws-samples/eks-workshop-v2#303]
### What happened?

I attempted to deploy an EKS cluster with the provide template to my region ca-central-1. It first failed with 
<details><summary> a Farget error for a specific availability zone: </summary>
<p>

```
╷
│ Error: creating Prometheus Workspace: RequestError: send request failed
│ caused by: Post "https://aps.ca-central-1.amazonaws.com/workspaces": dial tcp: lookup aps.ca-central-1.amazonaws.com on 172.16.153.81:53: no such host
│
│   with module.cluster.aws_prometheus_workspace.this,
│   on modules/cluster/amp.tf line 1, in resource "aws_prometheus_workspace" "this":
│    1: resource "aws_prometheus_workspace" "this" {
│
╵
╷
│ Error: creating EKS Fargate Profile (eks-workshop:checkout-profile): InvalidParameterException: Fargate Profile creation for the Availability Zone ca-central-1d for Subnet subnet-01854b3cde7463031 is not supported
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "aaac7cb7-e02a-4c7e-b950-6822aebd7107"
│   },
│   Message_: "Fargate Profile creation for the Availability Zone ca-central-1d for Subnet subnet-01854b3cde7463031 is not supported"
│ }
│
│   with module.cluster.module.eks_blueprints.module.aws_eks_fargate_profiles["checkout_profile"].aws_eks_fargate_profile.eks_fargate,
│   on .terraform/modules/cluster.eks_blueprints/modules/aws-eks-fargate-profiles/main.tf line 5, in resource "aws_eks_fargate_profile" "eks_fargate":
│    5: resource "aws_eks_fargate_profile" "eks_fargate" {
│
╵
```
</p></details>

Acknowledging this as a limitation, I attempted to destroy in order to change region. However, during destroy, Terraform failed with another error:
```
╷
│ Error: Unsupported attribute
│
│   on ide.tf line 20, in locals:
│   20: AMP_ENDPOINT=${module.cluster.amp_endpoint}
│     ├────────────────
│     │ module.cluster is object with 31 attributes
│
│ This object does not have an attribute named "amp_endpoint".
```

It appears that my first failure was at a point where the creation of AMP was not done. But when I tried to destroy it is expecting the value of `AMP_ENDPOINT`, which should be null checked.

### What did you expect to happen?

If Terraform apply fails, we should be able to destroy without failure, no matter at which point the apply failure occurred. 

### How can we reproduce it?

Set the default region to ca-central-1, and the template will use a zone that does not support Fargate profile creation.

### EKSversion

code: 1fbb013
EKS: 1.23

**Comment by niallthomson** [comment]
Hi @digihunch thanks for reporting this. We're working on trying to make the AZ selection more reliable.

With regards to destroy, we will push a fix in for this. Until then you can edit that line of the Terraform from this:

```
AMP_ENDPOINT=${module.cluster.amp_endpoint}
```

to this:

```
AMP_ENDPOINT=${try(module.cluster.amp_endpoint, "")}
```

**Comment by niallthomson** [comment]
The new workshop structure addresses this issue.
