### ISSUE TITLE
Typo in eksworkshop on configuring taints page

### ISSUE THREAD

**Issue by maddocash** [aws-samples/eks-workshop-v2#307]
## What would you like to be added/changed?

https://github.com/aws-samples/eks-workshop-v2/blob/c567a51624e573d7d443a5b0c71f3db7d11f0848/website/docs/fundamentals/managed-node-groups/taints/configuring-taints.md?plain=1#L100
`kubernets` --> `kubernetes`

**Comment by niallthomson** [comment]
Thanks for noticing this @maddocash !
