### ISSUE TITLE
Add AWS VPC Lattice to the workshop

### ISSUE THREAD

**Issue by sheetaljoshi** [aws-samples/eks-workshop-v2#315]
### What would you like to be added?

This chapter will focus on installing gateway-api controller and will explain the different APIs supported by gateway-api controller. We will demonstrate Lattice integrations and functions by building a secure application networking using the sample app used by EKS Workshop. We will demonstrate canary deployment. This module will also show how you can bring in Vanity names and bring your own cert.

### Why is this needed?

This is a launch feature and enable customers to use Amazon VPC Lattice.

**Comment by niallthomson** [comment]
Completed by #521
