### ISSUE TITLE
[feat] Add ArgoCD lab under Automation section

### ISSUE THREAD

**Issue by csantanapr** [aws-samples/eks-workshop-v2#319]
### What would you like to be added?

A an [ArgoCD](https://argo-cd.readthedocs.io/en/stable/) lab to the [Automation](https://www.eksworkshop.com/docs/automation) under the subsection [GitOps](https://www.eksworkshop.com/docs/automation/gitops/)
We already have [Flux lab](https://www.eksworkshop.com/docs/automation/gitops/flux/), users have requested to show the scenario with alternative tooling ArgoCD.

Both Flux and ArgoCD are graduated [CNCF projects](https://www.cncf.io/projects/).

### Why is this needed?

The Automation Working Group review the request, and define the lab content and requirements beyond following the expected [guidelines](https://github.com/aws-samples/eks-workshop-v2/blob/main/docs/authoring_content.md)

**Comment by huytn1219** [comment]
@csantanapr I can work on this [feat]. Can you assign it to me?

**Comment by csantanapr** [comment]
Hi @huytn1219 go ahead and start work on it, once you have you first iteration please open a Draft PR and linked back to this issue.

Thanks for volunteering !!!

**Comment by csantanapr** [comment]
Once you open a Draft PR I will move the issue to the "In Progress" in roadmap

**Comment by csantanapr** [comment]
To clarify the ArgoCD should follow same scenario as the Flux lab, meaning using kustomize for example

**Comment by ybezsonov** [comment]
Hi @csantanapr 
If you would require an [ArgoCD](https://argo-cd.readthedocs.io/en/stable/) lab to the [Automation](https://www.eksworkshop.com/docs/automation) under the subsection [GitOps](https://www.eksworkshop.com/docs/automation/gitops/) base on AWS Codecommit as a source repository, I would be glad to contribute.
