### ISSUE TITLE
[Bug]: workshop does not install using current instructions

### ISSUE THREAD

**Issue by aws-istavnit** [aws-samples/eks-workshop-v2#320]
### What happened?

1. Provisioned a brand new AWS Account.
2. Invited account to an AWS Organization. 
3. Followed instructions here: https://www.eksworkshop.com/docs/introduction/setup/your-account
4. When executing step `terraform apply --auto-approve` received the following error:

[ec2-user@ip-172-31-3-204 terraform]$ terraform apply --auto-approve 
module.ide.module.cloud9_bootstrap_lambda.data.external.archive_prepare[0]: Reading...
module.ide.module.cloud9_bootstrap_lambda.data.external.archive_prepare[0]: Read complete after 1s [id=-]
╷
│ Error: Invalid provider configuration
│ 
│ Provider "registry.terraform.io/hashicorp/aws" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as
│ described in the provider documentation.
│ 
╵
╷
│ Error: configuring Terraform AWS Provider: error validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, failed to resolve service endpoint, an AWS region is required, but was not found
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on <empty> line 0:
│   (source code not available)
│ 
╵
![image](https://user-images.githubusercontent.com/125827192/219970667-0ef84dff-9571-4d1e-95e0-e487b1b00412.png)

### What did you expect to happen?

Expected to have working workshop deployed.

### How can we reproduce it?

Follow instructions on https://www.eksworkshop.com/docs/introduction/setup/your-account

### EKSversion

None

**Comment by svennam92** [comment]
You need to add your AWS credentials for Terraform to pick them up. I suggest following the documented approach here:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

We should probably add some instructions to the workshop explaining this, fyi @ROunofF

**Comment by niallthomson** [comment]
I think we need to also clearly call out you need a region set, for example `AWS_REGION` or `AWS_DEFAULT_REGION`

**Comment by svennam92** [comment]
Fixed with https://github.com/aws-samples/eks-workshop-v2/commit/b70310cbd13265ddbd6842a3aaaef075d0f67854
