### ISSUE TITLE
error: no matches for kind "OpenTelemetryCollector" in version "opentelemetry.io/v1alpha1"

### ISSUE THREAD

**Issue by pachecoalbert** [aws-samples/eks-workshop-v2#335]
### What happened?

reset-environment
Resetting the environment, please wait
error: no matches for kind "OpenTelemetryCollector" in version "opentelemetry.io/v1alpha1"

### What did you expect to happen?

ran  - reset-environment

### How can we reproduce it?

reset-environment
Resetting the environment, please wait
error: no matches for kind "OpenTelemetryCollector" in version "opentelemetry.io/v1alpha1"

OR 

 kubectl apply -k /workspace/modules/observability/oss-metrics/adotserviceaccount/adot-collector unchanged
clusterrole.rbac.authorization.k8s.io/otel-prometheus-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/otel-prometheus-role-binding unchanged
configmap/otel-env-6kcf2bbb72 unchanged
error: unable to recognize "/workspace/modules/observability/oss-metrics/adot": no matches for kind "OpenTelemetryCollector" in version "opentelemetry.io/v1beta1"

### Anything else we need to know?

is there workaround to get eskworkshop working

### EKSversion

1.23

**Comment by niallthomson** [comment]
Hi @pachecoalbert I was unable to reproduce this on a fresh environment. Can you please provide the output of the following command in Cloud9:

```bash
kubectl get crd | grep opentelemetry
```

**Comment by pachecoalbert** [comment]
Hi 
Thank you for getting back to me so quickly.  I ran "kubectl get crd | grep opentelemetry" and it did not return anything.  No instance of "opentelemetry" was returned.
Regards,
Al

**Comment by pachecoalbert** [comment]
Hi, 
I took another look at the terraform apply on initial setup and noticed that it threw an error at the end so I reran it.  I now see that the "opentelemetry" has been deployed.
Thank you, again for you assistence.
Regards,
Al 

 kubectl get crd | grep opentelemetry
instrumentations.opentelemetry.io                                2023-02-28T13:42:48Z
opentelemetrycollectors.opentelemetry.io                         2023-02-28T13:42:48Z
