### ISSUE TITLE
[Bug]: Create Failed - Instances failed to join the kubernetes cluster on both Managed Ondemand & System Node Groups

### ISSUE THREAD

**Issue by Preenesh** [aws-samples/eks-workshop-v2#350]
### Installation method

Own AWS account

### What happened?

Setup of the environment in own AWS Account times out with Create Failed - Instances failed to join the kubernetes cluster on both Managed Ondemand & System Node Groups

### What did you expect to happen?

Setup was supposed launch required infra for the completing the workshop

### How can we reproduce it?

Use cloud9 with terraform version Terraform v1.3.9 installed , I am role with administrator privilege attached to cloud9  and cloud9 setup as per the old EKS workshop. Once done run setup steps from new EKS Workshop.

### Anything else we need to know?

Have used the EKS workshop supported regions 

### EKS version

1.23

**Comment by megazone-hcseo** [comment]
I also had a same problems so I fixed it with belowing code and I got success code 
it's not offical but I hope it will solve your problems too.

`
diff --git a/terraform/modules/cluster/ack.tf b/terraform/modules/cluster/ack.tf
index 9a6c997..6e7ce6c 100644
--- a/terraform/modules/cluster/ack.tf
+++ b/terraform/modules/cluster/ack.tf
@@ -3,7 +3,7 @@ locals {
 }

 module "ec2" {
-  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons/helm-addon?ref=v4.12.2"
+  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons/helm-addon?ref=v4.25.0"

   helm_config = {
     name             = local.ec2_name
diff --git a/terraform/modules/cluster/addons.tf b/terraform/modules/cluster/addons.tf
index bcd17e6..d7370ec 100644
--- a/terraform/modules/cluster/addons.tf
+++ b/terraform/modules/cluster/addons.tf
@@ -23,7 +23,7 @@ locals {
 }

 module "eks_blueprints_kubernetes_addons" {
-  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.16.0//modules/kubernetes-addons"
+  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.25.0//modules/kubernetes-addons"

   depends_on = [
     aws_eks_addon.vpc_cni
@@ -324,7 +324,7 @@ locals {
 }

 module "eks_blueprints_kubernetes_grafana_addon" {
-  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.16.0//modules/kubernetes-addons/grafana"
+  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.25.0//modules/kubernetes-addons/grafana"

   depends_on = [
     module.eks_blueprints_kubernetes_addons
diff --git a/terraform/modules/cluster/eks.tf b/terraform/modules/cluster/eks.tf
index ff9433d..cff8bf8 100644
--- a/terraform/modules/cluster/eks.tf
+++ b/terraform/modules/cluster/eks.tf
@@ -5,7 +5,7 @@ locals {
 }

 module "eks_blueprints" {
-  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.16.0"
+  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.25.0"

   tags = local.tags

diff --git a/terraform/modules/cluster/variables.tf b/terraform/modules/cluster/variables.tf
index f0b7a7c..1c4dae4 100644
--- a/terraform/modules/cluster/variables.tf
+++ b/terraform/modules/cluster/variables.tf
@@ -12,7 +12,7 @@ variable "cluster_version" {
 variable "ami_release_version" {
   description = "Default EKS AMI release version for node groups"
   type        = string
-  default     = "1.23.9-20221027"
+  default     = "1.23.9-20221104"
 }
`

**Comment by niallthomson** [comment]
Thanks for the report of this. So far I have not come across it happening and will need to investigate more to try to reproduce it.

**Comment by niallthomson** [comment]
This issue should no longer be applicable with the rearchitecture earlier this year, closing.
