### ISSUE TITLE
[Bug]: terraform eks created but no node add or generate

### ISSUE THREAD

**Issue by Hungmingh7609** [aws-samples/eks-workshop-v2#361]
### Installation method

Own AWS account

### What happened?

Hi we use the workshop from https://www.eksworkshop.com/docs/introduction/setup/your-account

and setup the aws credentials from aws cli, but terraform apply with error below

```
│ Warning: Helm release "ack-ec2" was created but has a failed status. Use the helm command to investigate the error, correct it, then run Terraform again.
│
│   with module.cluster.module.ec2.helm_release.addon[0],
│   on .terraform\modules\cluster.ec2\modules\kubernetes-addons\helm-addon\main.tf line 1, in resource "helm_release" "addon":│    1: resource "helm_release" "addon" {
│
╵
╷
│ Error: local-exec provisioner error
│
│   with module.cluster.null_resource.kubectl_set_env,
│   on modules\cluster\eks.tf line 217, in resource "null_resource" "kubectl_set_env":
│  217:   provisioner "local-exec" {
│
│ Error running command 'sleep 30
│ kubectl set env daemonset aws-node -n kube-system POD_SECURITY_GROUP_ENFORCING_MODE=standard --kubeconfig <(echo
│ $KUBECONFIG | base64 --decode)
│ sleep 10
│ ': exec: "/bin/bash": file does not exist. Output:
╵
╷
│ Error: timed out waiting for the condition
│
│   with module.cluster.module.ec2.helm_release.addon[0],
│   on .terraform\modules\cluster.ec2\modules\kubernetes-addons\helm-addon\main.tf line 1, in resource "helm_release" "addon":│    1: resource "helm_release" "addon" {
```

We found that the error was casuse by no node in k8s cluster, so the helm-release stage will timeout, also in aws console show no nodes available to schedule pods

![image](https://user-images.githubusercontent.com/24600064/223673952-b585b387-cbb9-4b19-964a-e7dccf2ddc98.png)

### What did you expect to happen?

terraform apply  succeese 

allow to https://www.eksworkshop.com/docs/introduction/setup/your-account work on next stage 

### How can we reproduce it?

follow by this step https://www.eksworkshop.com/docs/introduction/setup/your-account

then terraform init, terraform apply. 

wait for about 20 minute, then the error will show.

### Anything else we need to know?

we are current deploy in region eu-west-1

### EKS version

v1.23

**Comment by mlysenko01** [comment]
Had the same issue when was applying terraform from windows, switched to linux issue was resolved.

**Comment by shaharbar** [comment]
> ### Installation method
> Own AWS account
> 
> ### What happened?
> Hi we use the workshop from https://www.eksworkshop.com/docs/introduction/setup/your-account
> 
> and setup the aws credentials from aws cli, but terraform apply with error below
> 
> ```
> │ Warning: Helm release "ack-ec2" was created but has a failed status. Use the helm command to investigate the error, correct it, then run Terraform again.
> │
> │   with module.cluster.module.ec2.helm_release.addon[0],
> │   on .terraform\modules\cluster.ec2\modules\kubernetes-addons\helm-addon\main.tf line 1, in resource "helm_release" "addon":│    1: resource "helm_release" "addon" {
> │
> ╵
> ╷
> │ Error: local-exec provisioner error
> │
> │   with module.cluster.null_resource.kubectl_set_env,
> │   on modules\cluster\eks.tf line 217, in resource "null_resource" "kubectl_set_env":
> │  217:   provisioner "local-exec" {
> │
> │ Error running command 'sleep 30
> │ kubectl set env daemonset aws-node -n kube-system POD_SECURITY_GROUP_ENFORCING_MODE=standard --kubeconfig <(echo
> │ $KUBECONFIG | base64 --decode)
> │ sleep 10
> │ ': exec: "/bin/bash": file does not exist. Output:
> ╵
> ╷
> │ Error: timed out waiting for the condition
> │
> │   with module.cluster.module.ec2.helm_release.addon[0],
> │   on .terraform\modules\cluster.ec2\modules\kubernetes-addons\helm-addon\main.tf line 1, in resource "helm_release" "addon":│    1: resource "helm_release" "addon" {
> ```
> 
> We found that the error was casuse by no node in k8s cluster, so the helm-release stage will timeout, also in aws console show no nodes available to schedule pods
> 
> ![image](https://user-images.githubusercontent.com/24600064/223673952-b585b387-cbb9-4b19-964a-e7dccf2ddc98.png)
> 
> ### What did you expect to happen?
> terraform apply succeese
> 
> allow to https://www.eksworkshop.com/docs/introduction/setup/your-account work on next stage
> 
> ### How can we reproduce it?
> follow by this step https://www.eksworkshop.com/docs/introduction/setup/your-account
> 
> then terraform init, terraform apply.
> 
> wait for about 20 minute, then the error will show.
> 
> ### Anything else we need to know?
> we are current deploy in region eu-west-1
> 
> ### EKS version
> v1.23

+1

**Comment by Gall-oDrone** [comment]
I'm experience a similar problem: eks-workshop-cluster is created but neither pods nor nodes are created.

**EKS VERSION**
1.23
**Terraform version**
1.3.9
**OS**
macOs Monterey

I double checked my `~/.aws/config` and `~/.aws/credentials` with no issues displayed or typos.
Following the default configuration of github repo.

<img width="927" alt="Screen Shot 2023-07-01 at 15 26 03" src="https://github.com/aws-samples/eks-workshop-v2/assets/29985895/7d614cd0-229e-4989-bc93-035bb597a5f0">
<img width="929" alt="Screen Shot 2023-07-01 at 15 25 49" src="https://github.com/aws-samples/eks-workshop-v2/assets/29985895/34d4f6e3-45f4-4e97-8893-f118043aa13c">
<img width="930" alt="Screen Shot 2023-07-01 at 15 25 30" src="https://github.com/aws-samples/eks-workshop-v2/assets/29985895/5eb788e4-fd19-43f3-89d1-0e01502715cb">
<img width="943" alt="Screen Shot 2023-07-01 at 15 34 44" src="https://github.com/aws-samples/eks-workshop-v2/assets/29985895/9cbfb36b-ebdc-4bdc-b212-59bb69a9e2d5">
<img width="949" alt="Screen Shot 2023-07-01 at 15 34 35" src="https://github.com/aws-samples/eks-workshop-v2/assets/29985895/f64faff3-35d0-410a-864c-c81a11bb4f6b">

**Comment by niallthomson** [comment]
This will have been resolved by the new workshop structure that was just published. I'll close this for now and if there is a new occurrence please re-open.
