### ISSUE TITLE
New Observability Submodule - Kubernetes events and OpenSearch

### ISSUE THREAD

**Issue by alidonmez** [aws-samples/eks-workshop-v2#362]
### What would you like to be added?

The goal would be to add a module that integrates Kubernetes events with OpenSearch. Users would set-up an index and search through it for an error, and resolve it.

### Why is this needed?

Users would be exposed to Kubernetes events and OpenSearch. It would also help them understand types of events available, and how to use them for troubleshooting.

Could I please work on this enhancement if it's accepted?

**Comment by normalfaults** [comment]
The steps are: 1. pull this helm chart - https://artifacthub.io/packages/helm/bitnami/kubernetes-event-exporter, 2. set up an opensearch instance that's publicly available with a user/pass. 3. Enter user/pass info with other config info in helm values chart and deploy. 4. create a pod with an error - wrong image, port, etc. 5. user logs into opensearch, creates an index, and searches for errors. 6. finds pod error. 7. fixes pod spec and watches error disappear. Would this scenario work, and should I make any modifications?

**Comment by normalfaults** [comment]
@niallthomson any issues with the above plan ?

**Comment by allamand** [comment]
@normalfaults can it uses IRSA to authenticate on OpenSearch instead of login/password ?

**Comment by alidonmez** [comment]
@allamand 

I'll test and update you, but likely yes. Could the user log in with a username and password?

**Comment by alidonmez** [comment]
@allamand @normalfaults 

I couldn't get IRSA working. I created a role with proper permissions, created an iamserviceaccount and annotated it with the role info. The exporter didn't use the role and attempted to authn anonymously. I believe user/pass is required.

**Comment by alidonmez** [comment]
@normalfaults @allamand @niallthomson 

I'd like to use a helm chart, and after looking at the repo, it appears the other helm charts used are part of modules included in eks blueprints. Is this a requirement? Do I need to first add a module to eks blueprints, and then use it in the workshop?

**Comment by niallthomson** [comment]
Hi @alidonmez the chart being a part of blueprints is not a pre-requisite. You can see an example of where we implemented a "custom" addon here:

https://github.com/aws-samples/eks-workshop-v2/tree/main/terraform/modules/addons/descheduler
