### ISSUE TITLE
[Automation Lab] ArgoCD Tests

### ISSUE THREAD

**Issue by allamand** [aws-samples/eks-workshop-v2#367]
### What would you like to be added?

In this PR : https://github.com/aws-samples/eks-workshop-v2/pull/354 we added a new module for ArgoCD.

The modules tests are not written yet.

### Why is this needed?

This Issue is for tracking that we correctly test this module according to : https://github.com/aws-samples/eks-workshop-v2/blob/main/docs/automated_tests.md

**Comment by ybezsonov** [comment]
I can work on it

**Comment by csantanapr** [comment]
Thank you @ybezsonov 🎉
