### ISSUE TITLE
[Bug]: Terraform plan & apply fail with error "...planned value ...data_plane_wait_arn...does not match config value"

### ISSUE THREAD

**Issue by cloudopolis** [aws-samples/eks-workshop-v2#385]
### Installation method

Own AWS account

### What happened?

I cloned the project after installing Terraform as per the instructions on https://www.eksworkshop.com/docs/introduction/setup/your-account.  Terraform succesfully connects to AWS and generates all the changes required.  But it fails with:

Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/hashicorp/time" planned an invalid value for module.cluster.module.eks_blueprints_ack_addons.time_sleep.dataplane.triggers: planned value
│ cty.MapVal(map[string]cty.Value{"cluster_id":cty.UnknownVal(cty.String), "data_plane_wait_arn":cty.UnknownVal(cty.String)}) does not match config value
│ cty.MapVal(map[string]cty.Value{"cluster_id":cty.UnknownVal(cty.String), "data_plane_wait_arn":cty.UnknownVal(cty.String).RefineNotNull()}).
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

Here are the Terraform versions:
user@devbox:~/work/eks-workshop-v2/terraform$ terraform version
Terraform v1.4.1
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/grafana/grafana v1.34.0
+ provider registry.terraform.io/hashicorp/aws v4.58.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.16.1
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

Here is the error printed after displaying all the Changes

### What did you expect to happen?

I expect a successful plan & apply execution to be generated by terraform.

### How can we reproduce it?

Run on Ubuntu 22.04
Install the Terraform version (v1.4.1) and plugins listed above (all latest at the time of this writing).
Clone the https://github.com/aws-samples/eks-workshop-v2.git repo.  
Enter the ./eks-workshop-v2/terraform diretory.
Export valid AWS credentials to the Bash console.
Execute a "terraform plan" or "terraform apply" command.

### Anything else we need to know?

I'm running on Ubuntu 22.04

### EKS version

It doesn't get to a deploy stage so no version is deployed.

**Comment by Zero-Cool83** [comment]
Same.  Running Windows amd64

**Comment by luisalduucin** [comment]
Same, running on MacOS.

**Comment by niallthomson** [comment]
This seems to be traced back to a break in Terraform 1.4.1

https://github.com/hashicorp/terraform/issues/32859

**Comment by niallthomson** [comment]
I'm going to close this issue. If there are further incidences of this please re-open.
