### ISSUE TITLE
Upgrade to EKS 1.25

### ISSUE THREAD

**Issue by svennam92** [aws-samples/eks-workshop-v2#387]
Bump EKS version to 1.25

**Comment by csantanapr** [comment]
Hi @svennam92 
1. Is there going to be a branch with EKS 1.25 that we can test the automation labs?
2. Do you want each area (Automation, Observability, etc..) to create a tracking issue with owner, or you want to track all modules on this issue?

**Comment by svennam92** [comment]
@csantanapr As a rough plan, we start with creating a branch that bumps the version to 1.25, and run an e2e test suite. For test failures we can open issues and tag them with the appropriate label for each working group. We should also reference this issue so we have a view of all pending issues.

**Comment by csantanapr** [comment]
Should we make this one EKS 1.26?

Should each module section start testing with EKS 1.26 to see if there are any updates to be made to allow for the upgrade?

**Comment by svennam92** [comment]
I think we decided to stay on an n-1 version for the workshop, so let's stick with 1.25 for now. I believe @ROunofF may have an update on the upgrade process

**Comment by niallthomson** [comment]
Completed by #606
