### ISSUE TITLE
Upgrade Flux version in Flux lab

### ISSUE THREAD

**Issue by csantanapr** [aws-samples/eks-workshop-v2#389]
### What would you like to be added?

New version of Flux

### Why is this needed?

To keep up with latest bug and security fixes

**Comment by cornellanthony** [comment]
I can take this one

**Comment by candonov** [comment]
@cornellanthony any update on this?

**Comment by cornellanthony** [comment]
I'm working on it, will have something ready in the next few days.

**Comment by niallthomson** [comment]
This was resolved by #642
