### ISSUE TITLE
Upgrade ACK version in ACK lab

### ISSUE THREAD

**Issue by csantanapr** [aws-samples/eks-workshop-v2#390]
### What would you like to be added?

Update the ACK controllers (IAM, RDS, EC2) versions in ACK lab

### Why is this needed?

Keep up to date with bug and security fixes

**Comment by calmseas** [comment]
this is grant

**Comment by candonov** [comment]
@calmseas any update on this?

**Comment by niallthomson** [comment]
This was resolved by #712
