### ISSUE TITLE
Upgrade ArgoCD version for ArgoCD lab

### ISSUE THREAD

**Issue by csantanapr** [aws-samples/eks-workshop-v2#392]
### What would you like to be added?

Upgrade the version of ArgoCD helm chart used in terraform eks addon for the ArgoCD lab

### Why is this needed?

Keep up to date with bug and security fixes

**Comment by csantanapr** [comment]
@ybezsonov  is working on this as part of #376

**Comment by ybezsonov** [comment]
I can work on it

**Comment by csantanapr** [comment]
Thank you 🙏  @ybezsonov now I was able to assign to you
