### ISSUE TITLE
[Bug]: During installation timed out maybe

### ISSUE THREAD

**Issue by jtanton** [aws-samples/eks-workshop-v2#395]
### Installation method

Own AWS account

### What happened?

I am in WSL running terraform apply and I see these messages.....

module.ide.aws_lambda_invocation.cloud9_instance_profile: Creation complete after 2m16s [id=eks-workshop-cloud9-bootstrap_$LATEST_4d7de360f368023baf4d16c4d327e503]

│ Warning: Helm release "cert-manager" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.

│   with module.cluster.module.eks_blueprints_kubernetes_addons.module.opentelemetry_operator[0].module.cert_manager.module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/cluster.eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {

│ Error: Post "https://e66acfb7e69f8fbff30f9df638d4e323.gr7.us-east-1.eks.amazonaws.com/apis/apiextensions.k8s.io/v1/customresourcedefinitions?fieldManager=terraform-provider-helm_v2.9.0_x5": remote error: tls: bad record MAC
 with module.cluster.module.eks_blueprints_kubernetes_addons.module.opentelemetry_operator[0].module.cert_manager.module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/cluster.eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│

### What did you expect to happen?

I expected the apply to complete and the lab to be built.

### How can we reproduce it?

Not sure it is reproducible.  I ran apply again and it completed successfully.  Maybe a note in the install guide would help others.

### Anything else we need to know?

Niall thank you for the help working out the issue.

### EKS version

x

**Comment by Twiggles82** [comment]
I am getting the same error. I have tried running a terraform apply again but it still hasn't worked - any advice please?

Here is a full excerpt: - 

module.cluster.module.ec2.helm_release.addon[0]: Still creating... [18m51s elapsed]
╷
│ Error: local-exec provisioner error
│
│   with module.cluster.null_resource.kubectl_set_env,
│   on modules\cluster\eks.tf line 217, in resource "null_resource" "kubectl_set_env":
│  217:   provisioner "local-exec" {
│
│ Error running command 'sleep 30
│ kubectl set env daemonset aws-node -n kube-system POD_SECURITY_GROUP_ENFORCING_MODE=standard --kubeconfig <(echo $KUBECONFIG | base64 --decode)
│ sleep 10
│ ': exec: "/bin/bash": file does not exist. Output:
╵
╷
│ Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials
│
│   with module.cluster.module.ec2.helm_release.addon[0],
│   on .terraform\modules\cluster.ec2\modules\kubernetes-addons\helm-addon\main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {

**Comment by niallthomson** [comment]
@Twiggles82 it looks like you are running this in Windows. If so do you have access to WSL? We have an open issue to fix Windows compatibility.

**Comment by niallthomson** [comment]
@jtanton we've had a report of something similar separately. I believe running the Terraform again resolved the issue.

**Comment by Twiggles82** [comment]
@niallthomson - you are correct, I was trying to run on Windows. I then created a CentOS instance, ran it again and it worked a treat.

@jtanton - unfortunately even after re-running numerous times it still would not work for me in Windows.

**Comment by niallthomson** [comment]
This will have been resolved by the new workshop structure just published as you no longer need to run any commands on your local machine
