### ISSUE TITLE
[Bug]: Setup - 2 errors on terraform apply --auto-approve

### ISSUE THREAD

**Issue by KrisFernando** [aws-samples/eks-workshop-v2#402]
### Installation method

Own AWS account

### What happened?

After approximately 10 mins and the terraform apply is complete I get the 2 errors:
Error: local-exec provisioner error
│
│   with module.cluster.null_resource.kubectl_set_env,
│   on modules\cluster\eks.tf line 217, in resource "null_resource" "kubectl_set_env":
│  217:   provisioner "local-exec" {
│
│ Error running command 'sleep 30
│ kubectl set env daemonset aws-node -n kube-system POD_SECURITY_GROUP_ENFORCING_MODE=standard --kubeconfig <(echo $KUBECONFIG | base64     
│ --decode)
│ sleep 10
│ ': exec: "/bin/bash": file does not exist. Output:
╵
╷
│ Error: could not download chart: pulling from host public.ecr.aws failed with status code [manifests v0.1.0]: 403 Forbidden
│
│   with module.cluster.module.ec2.helm_release.addon[0],
│   on .terraform\modules\cluster.ec2\modules\kubernetes-addons\helm-addon\main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {

### What did you expect to happen?

I expected to have no errors similar to the video tutorial

### How can we reproduce it?

Follow the setup instructions.

### Anything else we need to know?

aws-cli/2.8.6 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

Terraform v1.4.0
on windows_amd64

Region: us-east-2 (ohio)

### EKS version

v 1.23

**Comment by njaved** [comment]
Did anyone have any luck with the issue? I'm also getting the same error and same OS.

**Comment by niallthomson** [comment]
All of these issues should have been resolved by the new workshop structure just published. I'll close this for now and please re-open if these issues occur again.
