### ISSUE TITLE
Workshop unable to deploy in isengard account.

### ISSUE THREAD

**Issue by phsmiths** [aws-samples/eks-workshop-v2#443]
Received same  error on existing account a new account. Both isengard accounts. 

module.cluster.module.ec2.helm_release.addon[0]: Still creating... [20m1s elapsed]
╷
│ Warning: Helm release "ack-ec2" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
│
│   with module.cluster.module.ec2.helm_release.addon[0],
│   on .terraform\modules\cluster.ec2\modules\kubernetes-addons\helm-addon\main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│
╵
╷
│ Error: local-exec provisioner error
│
│   with module.cluster.null_resource.kubectl_set_env,
│   on modules\cluster\eks.tf line 217, in resource "null_resource" "kubectl_set_env":
│  217:   provisioner "local-exec" {
│
│ Error running command 'sleep 30
│ kubectl set env daemonset aws-node -n kube-system POD_SECURITY_GROUP_ENFORCING_MODE=standard --kubeconfig <(echo $KUBECONFIG |
│ base64 --decode)
│ sleep 10
│ ': exec: "/bin/bash": file does not exist. Output:
╵
╷
│ Error: timed out waiting for the condition
│
│   with module.cluster.module.ec2.helm_release.addon[0],
│   on .terraform\modules\cluster.ec2\modules\kubernetes-addons\helm-addon\main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│
╵
\eks-workshop-v2\terraform>

**Comment by niallthomson** [comment]
Closing in favor of #395
