### ISSUE TITLE
[Bug]: argocd app create command fails due to incorrect kustomization 

### ISSUE THREAD

**Issue by cparik** [aws-samples/eks-workshop-v2#444]
### Installation method

Workshop Studio

### What happened?

In the automation lab for argocd. The app creation is failing because of incorrect kustomization.yaml.
Creating the argocd application fails with following error. 
```
$ argocd app create argocd-demo --repo https://github.com/aws-samples/eks-workshop-v2.git --path environment/workspace/modules/automation/gitops/argocd --dest-server https://kubernetes.default.svc --dest-namespace argocd-demo
FATA[0000] rpc error: code = InvalidArgument desc = application spec for argocd-demo is invalid: InvalidSpecError: Unable to generate manifests in environment/workspace/modules/automation/gitops/argocd: rpc error: code = Unknown desc = Manifest generation error (cached): `kustomize build .environment/workspace/modules/automation/gitops/argocd` failed exit status 1: Error: accumulating resources: accumulation err='accumulating resources from 'ui': evalsymlink failure on '.environment/workspace/modules/automation/gitops/argocd/ui' : lstat .environment/workspace/modules/automation/gitops/argocd/ui: no such file or directory': must build at directory: not a valid directory: evalsymlink failure on '.environment/workspace/modules/automation/gitops/argocd/ui' : lstat .environment/workspace/modules/automation/gitops/argocd/ui: no such file or directory 
```

### What did you expect to happen?

The application should be created. 

### How can we reproduce it?

Run the following command to create argocd as mentioned in the [workshop document](https://www.eksworkshop.com/docs/automation/gitops/argocd/deploy)
```
$ argocd app create argocd-demo --repo https://github.com/aws-samples/eks-workshop-v2.git --path environment/workspace/modules/automation/gitops/argocd --dest-server https://kubernetes.default.svc --dest-namespace argocd-demo
```

### Anything else we need to know?

This is due to the incorrect kustomization.yaml in `environment/workspace/modules/automation/gitops/argocd/`
```
environment/workspace/modules/automation/gitops/argocd/kustomization.yaml
--
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ui
```
There is no directory named `ui` in the `environment/workspace/modules/automation/gitops/argocd`.  As per the workshop documentation, it looks like the application being deployed is not `ui` but `catalog`. Thus, the kustomization.yaml should be as below. 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-demo
resources:
- ../../../../manifests/catalog/
```

### EKS version

1.23

**Comment by cparik** [comment]
Looks like the kustomization.yaml was changed in PR [#377](https://github.com/aws-samples/eks-workshop-v2/pull/377/files#diff-fcd0be11ca78dcb4051e6244a13cab7ca208da56d16a2969ec970a9a0b9d2d11)

**Comment by niallthomson** [comment]
Hi @cparik . This shouldn't not happen since we updated the command currently reads:

```
argocd app create argocd-demo --repo https://github.com/aws-samples/eks-workshop-v2.git --path environment/workspace/modules/automation/gitops/argocd --dest-server https://kubernetes.default.svc --dest-namespace argocd-demo --revision stable
```

Specifically it should have `--revision` at the end to avoid this problem you are having. Can you please confirm the command you are seeing?

**Comment by cparik** [comment]
It works with `--revision` at the end. This was not present in the workshop earlier.  Closing this ticket.
