### ISSUE TITLE
Graviton2 manage node groups lab

### ISSUE THREAD

**Issue by niallthomson** [aws-samples/eks-workshop-v2#456]
### Outline the high level topic of the lab

The ability to use Graviton-based EC2 instances with EKS is an important tool for potential cost savings and performance benefits. This lab would cover how to add these instances to an EKS cluster.

### Provide the flow of the lab exercise, including what sample application components will be used

The user should be directed to create a new EKS MNG with the AWS CLI that uses Graviton instance types. Then use node selectors to redeploy an application component (like the catalog) to the new nodes.

Prior art:
- [Graviton workshop](https://catalog.workshops.aws/graviton/en-US/amazoncontainers/amazoneks)
- [EKS Finhack](https://catalog.us-east-1.prod.workshops.aws/workshops/c4ab40ed-0299-4a4e-8987-35d90ba5085e/en-US/060-graviton)

### What additional AWS infrastructure or EKS addons/components will need to be created or installed to support this lab?

A new MNG will be created in the content.

### What additional software or configuration will be required in the Cloud9 IDE?

No

### Are enhancements to the retail sample application required to support this lab exercise?

No, already supports ARM CPU architecture

**Comment by niallthomson** [comment]
Unsure if we should cover building an ARM container image. All of the sample application components already provide multi-architecture images.

**Comment by arvind-v** [comment]
Can also demonstrate this by adding to the existing Karpenter section within Autoscaling. It would require:  
1. Additional Karpenter provisioner for Gravition instances and 
2. Updated nodeAffinity in deployment that limits to arm64
