### ISSUE TITLE
[Bug]: Cloud9 environment created but inaccessible through SSH or AWS Cloud9 Console

### ISSUE THREAD

**Issue by Gall-oDrone** [aws-samples/eks-workshop-v2#462]
### Installation method

Own AWS account

### What happened?

After running the command `terraform apply --auto-approve`resources, the cloud9 environment is not listed in the AWS Cloud9 console, although it is successfully created. I used the command ` AWS cloud9 describe-environments --environment-ids <cloud9-id>` which shows all the relevant information of the environment except its URL it even showed `"connectionType": "CONNECT_SSH"`. But it is still not shown in the AWS Cloud9 console.
I tried on different tested regions such as useast-2, uswest-2, and not tested regions like useast-1.

### What did you expect to happen?

After running the command `terraform apply --auto-approve` the cloud9 environment should be displayed in the AWS Cloud9 Management Console as stated in the EKS Workshop webpage.

### How can we reproduce it?

Follow-up step up steps in [https://www.eksworkshop.com/docs/introduction/setup/your-account](eksworkshop url)
1. Clone the EKS Workshop repository
2. `cd eks-workshop-v2/terraform`
3. `terraform init`
4. `terrafirm plan`
5. `terraform apply --auto-approve`
6. Wait until resources are created
7. Go to [https://us-east-1.console.aws.amazon.com/cloud9control/home?region=us-east-1#/product](cloud9 console)
8. Verify that the Cloud9 environment is already listed

### Anything else we need to know?

Installed version of terraform: `Terraform v1.3.9`
OS Unix
Mac OS Monterey 

### EKS version

1.23

**Comment by niallthomson** [comment]
Hi @Gall-oDrone, have you checked the information in this link? https://www.eksworkshop.com/docs/misc/cloud9-access
