### ISSUE TITLE
[Bug]: Issue with cloning code commit repo - Argo CD automation

### ISSUE THREAD

**Issue by ramasamy-seranthaiya** [aws-samples/eks-workshop-v2#470]
### Installation method

Workshop Studio

### What happened?

Initial Setup:
Step:
```
git clone $(cat ~/environment/argocd_repo_url) ~/environment/argocd
```

Error:
```
Cloning into '/home/ec2-user/environment/argocd'...
Access denied: User: arn:aws:iam::XXXXXXX:user/eks-workshop-gitops is not authorized to perform: codecommit:GitPull on resource: arn:aws:codecommit:us-west-2:xxxxxxxx:eks-workshop-argocd because no identity-based policy allows the codecommit:GitPull action
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### What did you expect to happen?

Git clone should have been successful

### How can we reproduce it?

Following the steps will recreate the issue

### Anything else we need to know?

IAM User "arn:aws:iam::xxxxxx:user/eks-workshop-gitops" has permissions to code commit repo eks-workshop-argocd but the code commit repo is created with eks-workshop-gitops name
```
{
    "Statement": [
        {
            "Action": [
                "codecommit:GitPush",
                "codecommit:GitPull"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:codecommit:us-west-2:xxxxx:eks-workshop-argocd",
            "Sid": ""
        }
    ],
    "Version": "2012-10-17"
}
```

### EKS version

1.23

**Comment by niallthomson** [comment]
Hi @ramasamy-seranthaiya were you trying to use eksworkshop.com content with Workshop Studio? Or the specific content referenced by the Workshop Studio content, which is currently https://build-ee0efb6.eksworkshop.com/docs/introduction/ide

**Comment by ramasamy-seranthaiya** [comment]
Hi @niallthomson Yes, I was trying to use eksworkshop.com content with Workshop studio. I missed the build version of the content

**Comment by ramasamy-seranthaiya** [comment]
Verified the workshop with the Workshop Studio Content and the labs worked fine. Closing the issue as non-issue
