### ISSUE TITLE
Error with terraform apply --auto-approve    

### ISSUE THREAD

**Issue by quangchustudy** [aws-samples/eks-workshop-v2#480]
### Installation method

Own AWS account

### What happened?

received an error
`
│ Error: could not download chart: pulling from host public.ecr.aws failed with status code [manifests v0.1.0]: 403 Forbidden
│ 
│   with module.cluster.module.ec2.helm_release.addon[0],
│   on .terraform/modules/cluster.ec2/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 
╵
╷
│ Error: could not download chart: pulling from host public.ecr.aws failed with status code [manifests v0.1.1]: 403 Forbidden
│ 
│   with module.cluster.module.eks_blueprints_ack_addons.module.rds[0].helm_release.addon[0],
│   on .terraform/modules/cluster.eks_blueprints_ack_addons.rds/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 
╵
╷
│ Error: could not download chart: pulling from host public.ecr.aws failed with status code [manifests v0.18.1]: 403 Forbidden
│ 
│   with module.cluster.module.eks_blueprints_kubernetes_addons.module.karpenter[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/cluster.eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 
╵
╷
│ Error: could not download chart: pulling from host public.ecr.aws failed with status code [manifests 1.97.0]: 403 Forbidden
│ 
│   with module.cluster.module.eks_blueprints_kubernetes_addons.module.kubecost[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/cluster.eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
`

### What did you expect to happen?

expect to finish without error

### How can we reproduce it?

run terraform apply --auto-approve    after terraform init 

### EKS version

1.23

**Comment by narikime** [comment]
I'm facing the same issue! Is there any workaround to move ahead. Now I can not use the whole lab :(

**Comment by niallthomson** [comment]
Hi folks, this issue should be resolved with the new workshop structure we just published. I'll close this for now and if you see similar issues please re-open.
