### ISSUE TITLE
[Bug]: Component deployment issue 

### ISSUE THREAD

**Issue by senthil-nathan** [aws-samples/eks-workshop-v2#486]
### Installation method

Own AWS account

### What happened?

Deploying other components as mentioned in https://www.eksworkshop.com/docs/introduction/getting-started/finish using 
kubectl apply -k /workspace/manifests 

### What did you expect to happen?

Expected to deploy all the components however I got the error:

$ kubectl apply -k workspace/manifests
error: rawResources failed to read Resources: Load from path rabbitmq failed: 'rabbitmq' must be a file (got d='/home/ec2-user/environment/eks-workshop-v2/environment/workspace/manifests/rabbitmq')

### How can we reproduce it?

run the command 

$ kubectl apply -k workspace/manifests

### EKS version

1.23

**Comment by niallthomson** [comment]
These file paths have changed with the workshop restructure and so this issue is no longer relevant
