### ISSUE TITLE
[Bug]: Document shows incorrect diagram

### ISSUE THREAD

**Issue by senthil-nathan** [aws-samples/eks-workshop-v2#487]
### Installation method

Own AWS account

### What happened?

https://build-ee0efb6.eksworkshop.com/docs/introduction/getting-started/first screenshot shows activemq instead of rabbitmq

### What did you expect to happen?

expect document (including screenshots to be reflecting code repo)

### How can we reproduce it?

not a code bug, document needs update

### EKS version

1.23

**Comment by ROunofF** [comment]
Diagram was updated in the latest version
