### ISSUE TITLE
Add lab exercise for the security and governance using Kubernetes policy engine Kyverno

### ISSUE THREAD

**Issue by patelrit** [aws-samples/eks-workshop-v2#488]
### Outline the high level topic of the lab

Kyverno is an open source policy engine and a CNCF incubating project. Kyverno can be used to enforce pod security and other best practices. Some relevant infomation can be found here:
[Enforcing Security Best Practices for Amazon EKS using Kyverno](https://aws.amazon.com/blogs/containers/managing-pod-security-on-amazon-eks-with-kyverno/)
[Enforcing Security Best Practices for Amazon EKS using Kyverno](https://nirmata.com/2023/04/04/enforcing-security-best-practices-for-amazon-eks-using-kyverno/)

### Provide the flow of the lab exercise, including what sample application components will be used

Lab exercise would include the following:
- Installing and configuring Kyverno
- Identifying and deploying relevant policies
- Viewing and understanding policy reports 
- Advanced exercises for automation, cost, image verification, etc can be included as well.

### What additional AWS infrastructure or EKS addons/components will need to be created or installed to support this lab?

Kyverno Policy Engine - Already available as EKS Add-on (via project sleek)

### What additional software or configuration will be required in the Cloud9 IDE?

Policies are written in YAML so a YAML editor will be required

### Are enhancements to the retail sample application required to support this lab exercise?

No other enhancements should be required

**Comment by chipzoller** [comment]
Hi there, @svennam92! Do you have any suggestions on what you all would like to see in such a module? Are you thinking this would go as an additional section [here](https://rearchitecture.eksworkshop.com/docs/security/pod-security-standards/) or as a sub-page like [here](https://rearchitecture.eksworkshop.com/docs/security/pod-security-standards/restricted)? I'd be glad to work something up based on what you think would be most helpful in the context of the workshop.

**Comment by chipzoller** [comment]
Any feedback on the above? Would this be better for a live discussion, @shapirov103?

**Comment by svennam92** [comment]
https://github.com/aws-samples/eks-workshop-v2/pull/800
