### ISSUE TITLE
[Bug]: Malformed json in iam.tf

### ISSUE THREAD

**Issue by gvasels-aws** [aws-samples/eks-workshop-v2#493]
### Installation method

Own AWS account

### What happened?

environment would not provision in a personal account with Administrator permissions. iam.tf returns an error calling out a malformed policy. This is because Sid is an empty string and requires a non-empty value for it to be valid.

### What did you expect to happen?

eksworkshop v2 - would expect terraform apply --auto-approve to run without error

### How can we reproduce it?

in your own AWS account, create a Cloud9 instance, follow the setup steps for your own account and once terraform apply --auto-approve starts to execute, you will see it fail part way through the deployment.

### Anything else we need to know?

I have addressed it and am submitting a PR

### EKS version

should be latest

**Comment by niallthomson** [comment]
This role no longer exists in the new workshop structure, closing this issue.
