### ISSUE TITLE
[Bug]: Issues trying to Setup workshop executing $ terraform apply --auto-approve

### ISSUE THREAD

**Issue by Valkyrjur** [aws-samples/eks-workshop-v2#498]
### Installation method

Own AWS account

### What happened?

Starting with the [Setup](https://www.eksworkshop.com/docs/introduction/setup/your-account) for "In your AWS account" it failed provisioning the resources after several minutes. I'm kinda beginner with Terraform, so I tried to run a $ terraform destroy to start again, more issues destroying what was created till that time because of dependencies. I ended deleting what I could manually. This is very frustrating because differently from the previous version of the workshop this deploys A LOT in your AWS account and you are not even able to follow the tutorials on your own EKS cluster.

```
(...)
module.cluster.module.eks_blueprints_kubernetes_grafana_addon.module.helm_addon.helm_release.addon[0]: Still creating... [1m10s elapsed]
module.cluster.module.eks_blueprints_kubernetes_grafana_addon.module.helm_addon.helm_release.addon[0]: Still creating... [1m20s elapsed]
module.cluster.module.eks_blueprints_kubernetes_grafana_addon.module.helm_addon.helm_release.addon[0]: Creation complete after 1m26s [id=grafana]
╷
│ Error: creating RDS DB Instance (eks-workshop-catalog): InvalidParameterCombination: Cannot find version 8.0.27 for mysql
│ 	status code: 400, request id: 3afeb78c-c16c-492c-b8d6-99c518261a20
│
│   with module.cluster.module.catalog_mysql.module.db_instance.aws_db_instance.this[0],
│   on .terraform/modules/cluster.catalog_mysql/modules/db_instance/main.tf line 32, in resource "aws_db_instance" "this":
│   32: resource "aws_db_instance" "this" {
```

### What did you expect to happen?

I expect it to work...

### How can we reproduce it?

You can reproducer it very easy, just follow 

```
$ git clone https://github.com/aws-samples/eks-workshop-v2.git
$ cd eks-workshop-v2
$ git checkout latest
$ cd terraform

$ terraform init
$ terraform apply --auto-approve 
```

BOOM BROKEN.

### Anything else we need to know?

Emphasis on how frustrating this is :( 

### EKS version

1.25 and Terraform v1.4.6

**Comment by niallthomson** [comment]
Hi @Valkyrjur thanks for the report. We're working on a fix for this, which appears to be limited to certain regions currently. Can you confirm which region you're using?

**Comment by Valkyrjur** [comment]
Thank you @niallthomson for the quick reply! 

It use eu-west-1. Do you have a list of the regions where it's working to try it in the meantime?

**Comment by niallthomson** [comment]
@Valkyrjur you should be able to use us-west-2. A fixed has been pushed but isn't promoted to the live version yet.
