### ISSUE TITLE
Adding estimated time to each lab

### ISSUE THREAD

**Issue by mirajranpura** [aws-samples/eks-workshop-v2#508]
### What would you like to be added?

There should be a widget in docusaurus to show-case the estimated timing for each lab. 

- EKS Overview 0:30
- Introduction 0:45
- - Setup / Accessing IDE 10m
- - Getting Started 22m
- - Kustomize (Optional) 8m
- Fundamentals 1:45

- - Managed Node Groups 45m
- - EKS upgrade 10-20m (SKIP)
- - Fargate 15m
- - Load Balancers (NLB) 15m
- - Ingress (ALB) 10m
- - EBS 10m
- - EFS 10m
- Autoscaling 0:40
- - Cluster Autoscaler 15m
- - Karpenter 10m
- - Horizontal Pod Autoscaler 6m
- - Cluster Proportional Autoscaler 6m
- Observability 1:30
- - View resources in EKS console 40m
- - Control plane logs 8m
- - Pod logging 5m
- - EKS open source observability 11m
- - Container Insights on EKS 10m
- - Cost visibility with Kubecost 9m
- Security 1:00
- - IAM Roles for Service Accounts 15m
- - Pod Security Standards 12m
- - Securing Secrets using Sealed Secrets 15m
- - Amazon GuardDuty for EKS 10m
- Networking 0:45
- - Security Groups for Pods 11m
- - Custom Networking 20m
- - Prefix Delegation 9m
- Automation 1:00
- - Flux 10m
- - Argo CD 15m
- - AWS Controllers for Kubernetes 30m
- - Crossplane 30m

### Why is this needed?

A ball park time estimation for each section can help attendees to focus on labs. Having this as a widget, the attendees start/stop timer etc if needed.  This may help to surface the estimated time for each lab.

**Comment by niallthomson** [comment]
This was completed in #634
