### ISSUE TITLE
[feat] - Add Flux lab to demonstrate CI + Flux Image automation controller for image patching

### ISSUE THREAD

**Issue by ybezsonov** [aws-samples/eks-workshop-v2#511]
### Outline the high level topic of the lab

The purpose of the lab is to show how to make a change in the source code of one of the a retail sample components, build a new container images and deploy this images to the EKS cluster automatically. This could describe a simple developer workflow from the source to deployed image.

### Provide the flow of the lab exercise, including what sample application components will be used

- clone source code of one of the a retail sample components (ui?) to the Cloud9 environment
- clone empty AWS Codecommit repository created during workshop setup 
- copy sources to AWS Codecommit folder
- change sources
- git push to AWS CodeCommit to the main branch
- change in the main branch triggers AWS Codepipeline
- AWS Codepipeline starts AWS Codebuild to build an image
- AWS Codebuild builds and image and pushes it to private Amazon ECR
- Flux Image automation controller detect new image and update deployment manifest with new image tag
- Flux reconcile the app and deploy new image
- the learner can test new image 

### What additional AWS infrastructure or EKS addons/components will need to be created or installed to support this lab?

- AWS Codecommit repository for source code of a retail sample component
- AWS Codepipeline
- AWS CodeBuild to build a new image
- private Amazon ECR to store a new image
- Flux Image automation controller

### What additional software or configuration will be required in the Cloud9 IDE?

none

### Are enhancements to the retail sample application required to support this lab exercise?

none

**Comment by niallthomson** [comment]
Implemented in #642
