### ISSUE TITLE
[Bug]: Docs instruct to use latest tag which is old commit Feb 16

### ISSUE THREAD

**Issue by csantanapr** [aws-samples/eks-workshop-v2#517]
### Installation method

Own AWS account

### What happened?

Following the instruction to setup on own aws account, it tells the user to use `latest` tag to checkout from git
https://www.eksworkshop.com/docs/introduction/setup/your-account#provisioning
```bash
git clone https://github.com/aws-samples/eks-workshop-v2.git
cd eks-workshop-v2
git checkout latest
cd terraform
```

### What did you expect to happen?

I'm expecting to use the latest stable version of the workshop that is located in `main` branch

### How can we reproduce it?

try the instructions

### EKS version

N/A

**Comment by niallthomson** [comment]
This was fixed by linked PR
