### ISSUE TITLE
Have flux already installed on the cluster

### ISSUE THREAD

**Issue by csantanapr** [aws-samples/eks-workshop-v2#528]
### What would you like to be added?

Having flux already installed in the cluster it simplifies and make it consistent with other labs like argocd

Use helm to install
https://github.com/fluxcd-community/helm-charts

### Why is this needed?

The terraform setup of the cluster would need to be updated to install the helm chart of flux.
Investigate if bootstrap is need it or it can also be done as part of terraform setup.
If its simple do this changes we want to do it now, if becomes too complex then will wait for the new architecture of workshop that each lab/module would have their own setup/start and end scripts.

cc @niallthomson

**Comment by hellenavilarosa** [comment]
Assign to me, please!

**Comment by niallthomson** [comment]
With the restructure we've moved away from pre-installing components like this, so I'm closing this issue.
