### ISSUE TITLE
[Bug]: Error: Unsupported argument

### ISSUE THREAD

**Issue by GabrielAWS** [aws-samples/eks-workshop-v2#538]
### Installation method

Own AWS account

### What happened?

Hi everyone!

I am starting terraform init and terraform apply --auto-approve, but when it runs, it is generating the following warning and error messages:
╷
│ **Warning: Argument is deprecated**
│ 
│   with module.cluster.module.aws_vpc.aws_eip.nat,
│   on .terraform/modules/cluster.aws_vpc/main.tf line 1013, in resource "aws_eip" "nat":
│ 1013:   vpc = true
│ 
│ use domain attribute instead
╵
╷
│ **Error: Unsupported argument**
│ 
│   on .terraform/modules/cluster.aws_vpc/main.tf line 35, in resource "aws_vpc" "this":
│   35:   enable_classiclink             = null # https://github.com/hashicorp/terraform/issues/31730
│ 
│ An argument named "enable_classiclink" is not expected here.
╵
╷
│ **Error: Unsupported argument**
│ 
│   on .terraform/modules/cluster.aws_vpc/main.tf line 36, in resource "aws_vpc" "this":
│   36:   enable_classiclink_dns_support = null # https://github.com/hashicorp/terraform/issues/31730
│ 
│ An argument named "enable_classiclink_dns_support" is not expected here.
╵
╷
│ **Error: Unsupported argument**
│ 
│   on .terraform/modules/cluster.aws_vpc/main.tf line 1246, in resource "aws_default_vpc" "this":
│ 1246:   enable_classiclink   = null # https://github.com/hashicorp/terraform/issues/31730
│ 
│ An argument named "enable_classiclink" is not expected here.
╵

**How can this be resolved?**

### What did you expect to happen?

Start infrastructure creation.

### How can we reproduce it?

git clone https://github.com/aws-samples/eks-workshop-v2.git
cd eks-workshop-v2
git checkout latest
cd terraform
terraform init
terraform apply --auto-approve

### EKS version

--

**Comment by jrob421** [comment]
Running into the same issue. Let me know if you find a workaround

**Comment by gaborho** [comment]
Hi, I had the same issue. When I used instructions here, it worked: https://build-4829020.eksworkshop.com/docs/introduction/setup/your-account/
Notice that it is checking out build-4829020, not latest.

**Comment by vyshnavi753** [comment]
AWS_VPC version is 3.9.1 After changing it to the latest version(currently 5.0.0), it worked for me. 
https://github.com/aws-samples/eks-workshop-v2/blob/7b044d68011fbde96c3a7841e04f95096e0aa2f4/terraform/modules/cluster/vpc.tf#L14

**Comment by niallthomson** [comment]
This has been resolved for now by pinning the provider to < 5.0 This was just published.

**Comment by nwokoloemmanuel6** [comment]
> S_VPC version is 3.9.1 After ch

pls i did the same and it didn't work is there something else you did?

**Comment by pengc99** [comment]
> 

You should now be able to continue running the install by keeping the line item mentioned in https://github.com/aws-samples/eks-workshop-v2/issues/538#issuecomment-1574028948 back to 3.19.0

**Comment by agun21st** [comment]
100% Confirmed that updating version to 5.0.0 worked for me as well

**Comment by myroslavmail** [comment]
> > S_VPC version is 3.9.1 After ch
> 
> pls i did the same and it didn't work is there something else you did?

Be aware to upgrade module that you use. VPC module, you need to change version there, it's not about aws provider version. Don't mess up with those two. Or at least you need to check both AWS provider version, and module version that you use.

**Comment by Kris20030907** [comment]
It also works if I upgrade the vpc version to 5.0.0

**Comment by niallthomson** [comment]
@Kris20030907 this should have been resolved quite a while ago, we made changes to the versions used.
