### ISSUE TITLE
[Bug]: archive.eksworkshop.com certifcate expired

### ISSUE THREAD

**Issue by hardillb** [aws-samples/eks-workshop-v2#563]
### Installation method

Own AWS account

### What happened?

The certificate for archive.eksworkshop.com expired on the 21st May

### What did you expect to happen?

The cert to be updated.

### How can we reproduce it?

https://archive.eksworkshop.com/beginner/080_scaling/test_ca/

### EKS version

NA

**Comment by niallthomson** [comment]
This issue was resolved earlier this month
