### ISSUE TITLE
[Bug]: ingress workshop miss IAM permisssion

### ISSUE THREAD

**Issue by xufanglin** [aws-samples/eks-workshop-v2#564]
### Installation method

Workshop Studio

### What happened?

hello,I launched ingress workshop,and fail to create ingress resource.

Error log:
```
WSParticipantRole:~/environment $ kubectl apply -k /workspace/modules/exposing/ingress/creating-ingress
ingress.networking.k8s.io/ui created

WSParticipantRole:~/environment $ kubectl get ing -n ui
NAME   CLASS   HOSTS   ADDRESS   PORTS   AGE
ui     alb     *                 80      7s

WSParticipantRole:~/environment $ aws elbv2 describe-load-balancers --query 'LoadBalancers[?contains(LoadBalancerName, `k8s-ui-ui`) == `true`]'
[]

WSParticipantRole:~/environment $ kubectl describe -n ui ingress ui                                                                                            
Name:             ui
Labels:           <none>
Namespace:        ui
Address:          
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  *           
              /   ui:80 (10.42.10.189:8080)
Annotations:  alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/liveness
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
Events:
  Type     Reason             Age    From     Message
  ----     ------             ----   ----     -------
  Warning  FailedDeployModel  5m24s  ingress  Failed deploy model due to AccessDenied: User: arn:aws:sts::098731804397:assumed-role/eks-workshop-aws-load-balancer-controller-sa-irsa/1686716483345551291 is not authorized to perform: elasticloadbalancing:AddTags on resource: arn:aws:elasticloadbalancing:us-west-2:098731804397:targetgroup/k8s-ui-ui-2ea639362d/* because no identity-based policy allows the elasticloadbalancing:AddTags action
           status code: 403, request id: 750c4163-c48c-45e2-a36a-9465317900c2
  Warning  FailedDeployModel  5m23s  ingress  Failed deploy model due to AccessDenied: User: arn:aws:sts::098731804397:assumed-role/eks-workshop-aws-load-balancer-controller-sa-irsa/1686716483345551291 is not authorized to perform: elasticloadbalancing:AddTags on resource: arn:aws:elasticloadbalancing:us-west-2:098731804397:targetgroup/k8s-ui-ui-2ea639362d/* because no identity-based policy allows the elasticloadbalancing:AddTags action
           status code: 403, request id: 1d70f3eb-7eb8-4b59-bbb4-5c8f4036da88
```

How to fix:
I add `elasticloadbalancing:AddTags` permission to `eks-workshop-lb-irsa` policy,and recreate ingress resource,it's work.

### What did you expect to happen?

create ingress resource sucess when i used follow command:
`kubectl apply -k /workspace/modules/exposing/ingress/creating-ingress`

### How can we reproduce it?

lanuch workshop: https://www.eksworkshop.com/docs/fundamentals/exposing/ingress/adding-ingress

### EKS version

WSParticipantRole:~/environment $ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:26:51Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-c12679a", GitCommit:"d5ce2cee85d99653d6f8c278043213db21b1cd72", GitTreeState:"clean", BuildDate:"2023-05-22T20:32:28Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by henriquesantanati** [comment]
It also happens while [creating NLB](https://www.eksworkshop.com/docs/fundamentals/exposing/loadbalancer/adding-lb) following the first `apply` command after the `reset-environment` on the [Load Balancers](https://www.eksworkshop.com/docs/fundamentals/exposing/loadbalancer/) page

**Comment by henriquesantanati** [comment]
I could see that the [workshop is using tag v4.16.0](https://github.com/aws-samples/eks-workshop-v2/blob/main/terraform/modules/addons/descheduler/main.tf) which points to [this policy](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/v4.16.0/modules/kubernetes-addons/aws-load-balancer-controller/data.tf). 

[This commit](https://github.com/aws-ia/terraform-aws-eks-blueprints/commit/9a76dbb404375bde118aabc33fc4acd3220c82df) might resolve the issue.

**Comment by niallthomson** [comment]
Looking in to this issue

**Comment by niallthomson** [comment]
I've hot fixed this for any fresh clones, working on fix instructions for existing environments

**Comment by niallthomson** [comment]
Running this in Cloud9 will temporarily unblock any environments suffering from this:

```
cat << EOF > alb-iam-patch.json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "elasticloadbalancing:AddTags",
            "Effect": "Allow",
            "Resource": "*",
            "Sid": "patch"
        }
    ]
}
EOF

aws iam put-role-policy --role-name eks-workshop-aws-load-balancer-controller-sa-irsa --policy-name alb-patch-policy --policy-document file://alb-iam-patch.json
```

**Comment by fptiangco** [comment]
Thanks, @niallthomson. That worked.
I'll look out for any permanent fixes.

**Comment by niallthomson** [comment]
The new workshop structure that was just released uses an updated mechanism for the load balancer controller that should not have this issue. Closing.
