### ISSUE TITLE
Add Crossplane Labs (Nested Compositions, GitOps, OPA/Gatekeeper)

### ISSUE THREAD

**Issue by csantanapr** [aws-samples/eks-workshop-v2#565]
### What would you like to be added?

Enhance the Crossplane lab with additional sections
- Nested Compositions (Using the composition from previous section)
- Deploy a Claim using GitOps using the Nested Composition
- Add a section on Policy Engines show how to work with Crossplane resources using OPA and Gatekeeper

### Why is this needed?

Customer asked for a GitOps and Crossplane workshop that included how to work with nested composition, deploy with argocd, and how to enforce policies on crossplane resources

**Comment by niallthomson** [comment]
Going to close this for now as stale
