### ISSUE TITLE
[Bug]: destroy not able to delete everything

### ISSUE THREAD

**Issue by AvinashDalvi89** [aws-samples/eks-workshop-v2#567]
### Installation method

Own AWS account

### What happened?

I tried this lab https://www.eksworkshop.com/docs/introduction/setup/your-account after checking trying to destroy but not getting destroy. 
<img width="1224" alt="Screenshot 2023-06-14 at 7 25 46 PM" src="https://github.com/aws-samples/eks-workshop-v2/assets/3996105/a0733b9a-a569-4f4d-a5db-576a66655274">

### What did you expect to happen?

It should delete all resources. 

### How can we reproduce it?

Try similar steps mentioned above workshop document. 

### EKS version

1.23

**Comment by twarnock** [comment]
If I wait I get a timeout after about 20 minutes: `Error: uninstallation completed with 1 error(s): timed out waiting for the condition`

**Comment by niallthomson** [comment]
Is there any indication in the cluster that Grafana is being blocked from deletion? Some output from `kubectl -n grafana get pods` and `kubectl get namespace grafana` would be helpful.

**Comment by niallthomson** [comment]
This issue should be mitigated by the rearchitecture work that was completed earlier this year, closing this issue unless more information provided.
