### ISSUE TITLE
Add network policy chapter to Security section of EKS Workshop

### ISSUE THREAD

**Issue by sheetaljoshi** [aws-samples/eks-workshop-v2#588]
### What would you like to be added?

Amazon EKS is planning to launch native Network Policy support within Amazon VPC CNI. The chapter will help customers understand different components and implementation details.

### Why is this needed?

The chapter will be a launch material helping customers with adoption of network policies. With native support for network policy in Amazon VPC CNI, when running Kubernetes on AWS, you can now create policies that isolate sensitive workloads protecting them from potential threats. Network policies also helps you achieve compliance with regulatory requirements by enforcing access controls and preventing unauthorized access to critical resources. This level of granular control enables you to implement the principle of least privilege, ensuring that only authorized pods can communicate with each other and that unauthorized access attempts are blocked. Network policies provide defense-in-depth mechanism, allowing you to extend the security features provided by Amazon VPC, such as [EC2 security groups](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-groups.html) (SGs) and [network access control lists](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html) (NACLs).

**Comment by niallthomson** [comment]
Closing as duplicate of #228
