### ISSUE TITLE
[Bug]: EKS workshop timeout and error while setting up 

### ISSUE THREAD

**Issue by Gall-oDrone** [aws-samples/eks-workshop-v2#591]
### Installation method

Own AWS account

### What happened?

Terraform tries to create resources but after a 20 minutes timeout it shows the errors below:

<img width="1205" alt="Screen Shot 2023-07-09 at 11 44 15" src="https://github.com/aws-samples/eks-workshop-v2/assets/29985895/9e940b00-3adb-480f-957c-1fac094f9815">

I tested on different regions with the same output. Not sure what's causing the timeout followed by the errors shown above.

Similar issues found here #395  and #361 

### What did you expect to happen?

Initialize the EKS Workshop configuration without errors or timeouts.

### How can we reproduce it?

Run:

1.  Follow set up instructions stated in the corresponding EKS Workshop section
3. `terraform init`
4. `terraform plan`
5. `terraform apply --auto-approve`

### Anything else we need to know?

I already tested on different regions such us-east-1, us-east-2, and us-west-2 as stated in the EKS documentation. Still getting the same result. This error started showing after I pull the latest eks repository.

MacOS: Monterey 12.6.3
Terraform version: 1.3.9

### EKS version

1.23

**Comment by allamand** [comment]
It seams that you have existing iam roles that have the same name as the one created by the workshop. You need to delete them before applying again the terraform

**Comment by Gall-oDrone** [comment]
Hi allamand,

Before running `terraform apply --auto-approve` I always make sure to manually delete all EKS resources from AWS including any KMS keys from previous deployments. 
I suspect that the error `Entity already exists` is because there might be a bug during the 20 minutes timeout that generates twice the same resouce e.g. `IAM role`.
I also tried deleting all IAM roles and policies and re-run `terraform apply --auto-approve`, but got the same result.

**Comment by niallthomson** [comment]
Hi @Gall-oDrone  this should be resolved by the new workshop structure we just published as we've moved away from that Terraform. Please give that a try. I'll close this issue for now and if you run in to further issues please re-open it.
