### ISSUE TITLE
[Bug]: Unable to provision lab

### ISSUE THREAD

**Issue by danny-yeshurun** [aws-samples/eks-workshop-v2#600]
### Installation method

Own AWS account

### What happened?

Following the instructions here - https://www.eksworkshop.com/docs/introduction/setup/your-account
I am getting this error:
```
module.cluster.module.eks_blueprints_kubernetes_addons.module.kubecost[0].module.helm_addon.helm_release.addon[0]: Creating...
╷
│ Error: cannot re-use a name that is still in use
│ 
│   with module.cluster.module.eks_blueprints_kubernetes_addons.module.kubecost[0].module.helm_addon.helm_release.addon[0],
│   on .terraform/modules/cluster.eks_blueprints_kubernetes_addons/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 
╵
```

### What did you expect to happen?

Lab to be provisioned successfully

### How can we reproduce it?

🤷 

### EKS version

1.2.13

**Comment by niallthomson** [comment]
Hi @danny-yeshurun this should be resolved by the new workshop structure we just published as we've moved away from that Terraform. Please give that a try. I'll close this issue for now and if you run in to further issues please re-open it.
