### ISSUE TITLE
[Bug]:  us-west-1 region only has 2 AZs, but the eks cluster is built on 3 AZs

### ISSUE THREAD

**Issue by Niemetz** [aws-samples/eks-workshop-v2#619]
### Installation method

Own AWS account

### What happened?

you said:
This section outlines how to set up the environment to run the labs in your own AWS account. These instructions have been tested in the following AWS regions and are not guaranteed to work in others without modification:

us-west-2
eu-west-1

So,  I selected us-west-1 in my account

### What did you expect to happen?

When you are about to create an eks cluster, the code says that you are about to built a cluster across 2 AZs:

availabilityZones:
- ${AWS_REGION}a
- ${AWS_REGION}b
- ${AWS_REGION}c

With this , I do not not think that this deployment will work, since region us-west-1 only has 2 AZs namely : us-west-1b and us-west-1c.

### How can we reproduce it?

Try to create a subnet, you will see that you can select either us-west-1b or us-west-1c

### Anything else we need to know?

You would probably want to build and test your workshop in us-east-1 so that you can deploy eks cluster in three AZs.

### EKS version

I used the eks version in AWS on August-01-23.  
I checked the code that is used to create eks cluster and it says: version: '1.25'

**Comment by ROunofF** [comment]
I'm worry but us-west-1 is not supported by the EKS workshop. You're free to change the file locally to have it run over there
