### ISSUE TITLE
Reword VPC Lattice preamble

### ISSUE THREAD

**Issue by niallthomson** [aws-samples/eks-workshop-v2#623]
### What would you like to be added?

The preamble to the VPC Lattice module currently says:

> This module currently only works on the [self-hosted version](https://www.eksworkshop.com/docs/introduction/setup/your-account) of eksworkshop as Amazon VPC Lattice resources are not yet supported [at an AWS Event](https://www.eksworkshop.com/docs/introduction/setup/aws-event).

The lab should now be usable at AWS events.

### Why is this needed?

Changes to the Workshop Studio platform should make it possible for this module to be run at AWS events now.

**Comment by C123R** [comment]
@niallthomson Could you please assign this issue to me?
