### ISSUE TITLE
Migrate to kubectl 1.25

### ISSUE THREAD

**Issue by niallthomson** [aws-samples/eks-workshop-v2#624]
### What would you like to be added?

The workshop will need to migrate from the approach outlined in the link below to using `envsubst` to substitute in environment variables to kustomize manifests.

https://mbuffa.github.io/tips/20210720-kustomize-environment-variables/

The approach that will need to be taken will probably be:

```
kustomize build <path> | envsubst | kubectl apply -f -
```

### Why is this needed?

Currently the mechanism used to substitute environment variables in to kustomize manifests has been removed in subsequent versions of `kubectl`. We need to unlock being able to move forward the version of `kubectl` that we're using.

**Comment by mylesw42** [comment]
From what I can tell envsubst works for variables in ${var} or $var format in files. Not all modules in the workshop are following this pattern. There is a mix of ${var} and $(var) format. Also, modules are already using configMapGenerator, but are taking advantage of the old "feature" that would lookup the ENV var of the specified name in the properties file.

If the properties files are updated to be "ENV=value", the more recent versions of `kubectl kustomize` or `kustomize build` commands will substitute the values fine.

I think we could populate these env properties files just before, and maintain the existing commands and configuration.

I did a successful test on the karpenter module with this approach. Further testing would need to be done to fully validate more complex modules.

**Comment by mylesw42** [comment]
This is not a blocker until workshop moves to kubectl v1.27.0.

**Comment by niallthomson** [comment]
Resolved by #739
