### ISSUE TITLE
Migrate Crossplane and ACK labs to DynamoDB

### ISSUE THREAD

**Issue by niallthomson** [aws-samples/eks-workshop-v2#625]
### What would you like to be added?

Center the Crossplane and ACK labs around provisioning a DynamoDB table for the carts component, instead of using RDS with the catalog.

### Why is this needed?

Provisioning an RDS database is time consuming and means that the lab takes longer than it ideally would, with much of the time spent waiting for the database to create. Moving to DynamoDB would make the lab more time-effective.

**Comment by thiru85** [comment]
I can pick this up

**Comment by thiru85** [comment]
working on it!
