### ISSUE TITLE
[Bug]: Error at IAM Roles for Service Accounts

### ISSUE THREAD

**Issue by jrogatis** [aws-samples/eks-workshop-v2#629]
### Installation method

Workshop Studio

### What happened?

When im testing the workshop at Security step. 

prepare-environment security/irsa

Give me:
Error from server (InternalError): error when creating "/eks-workshop/manifests/modules/security/irsa/.workshop/manifests": Internal error occurred: failed calling webhook "mservice.elbv2.k8s.aws": failed to call webhook: Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/mutate-v1-service?timeout=10s": no endpoints available for service "aws-load-balancer-webhook-service"

### What did you expect to happen?

create a Security environment to lab

### How can we reproduce it?

just go to IAM Roles for Service Accounts
at Security 
and run prepare-environment security/irsa

### EKS version

version 1.25

**Comment by mylesw42** [comment]
@jrogatis Confirmed I see the same error when testing that module. You can confirm that the infrastructure is applied successfully by looking at the `/tmp/terraform-apply.log`. You should see something similar to `Apply complete! Resources: 11 added, 0 changed, 0 destroyed.`

The error from what I can gather is from the `kubectl apply` command which is executed after the terraform apply. If the load balancer service is not available, the `ui-nlb` service in the ui namespace will not be deployed, and the NLB will not be configured.

If you haven't already done so. Try to deploy again:

`$ cd ~/environment/eks-workshop/modules/security/irsa`
`$ kubectl apply -k .workshop/manifests/`
 
It seems like the AWS load balancer controller is not ready quick enough to accept the request. The infra/kubectl scripts on the backend of this may need some tweaking for a "delay" of some sort just to allow for things to start up successfully.
