### ISSUE TITLE
[Bug]: prepare-environment fails

### ISSUE THREAD

**Issue by panicboat** [aws-samples/eks-workshop-v2#633]
### Installation method

Own AWS account

### What happened?

I tried this lab https://www.eksworkshop.com/docs/fundamentals/managed-node-groups/
```bash
AWSReservedSSO_AWSAdministratorAccess_f927e76eb8ab9447:~/environment $ prepare-environment fundamentals/mng
Refreshing copy of workshop repository from GitHub...

Resetting the environment, please wait
Waiting for application to become ready...
Cleaning up previous lab infrastructure...
Creating infrastructure for next lab...
bash: line 128: EKS_DEFAULT_MNG_MIN: unbound variabl
AWSReservedSSO_AWSAdministratorAccess_f927e76eb8ab9447:~/environment $ 
AWSReservedSSO_AWSAdministratorAccess_f927e76eb8ab9447:~/environment $ eksctl get nodegroup --cluster $EKS_CLUSTER_NAME --name $EKS_DEFAULT_MNG_NAME
Error: flag needs an argument: --name
```

### What did you expect to happen?

The list of node groups should have been displayed, but in fact the command was an error!

### How can we reproduce it?

This will occur if `prepare-environment` is run after the Introduction step is completed.

### EKS version

v1.25.6

**Comment by niallthomson** [comment]
Hi @panicboat , did you run the `use-cluster` command prior to this? It should be something like:

```
use-cluster eks-workshop
```

**Comment by panicboat** [comment]
@niallthomson Thanks, I ran use-cluster and it worked.
I will make sure to run use-cluster every Step.
