### ISSUE TITLE
[Bug]: Missing Fundamentals/Taints provisioning 

### ISSUE THREAD

**Issue by reuser** [aws-samples/eks-workshop-v2#640]
### Installation method

Own AWS account

### What happened?

Taints group is not provisioned, also $EKS_TAINTED_MNG_NAME  variable seems to be not set. 
`ec2-user:~/environment $ eksctl get nodegroup --name $EKS_TAINTED_MNG_NAME --cluster $EKS_CLUSTER_NAME 
Error: operation error EKS: DescribeNodegroup, https response error StatusCode: 404, RequestID: 9b6c7596-087a-4ccc-917d-9a0b8b2d6aa1, ResourceNotFoundException: No node group found for name: taint-mng.`

### What did you expect to happen?

Have taint nodegroup provisioned and $EKS_TAINTED_MNG_NAME var set properly

### How can we reproduce it?

Execute step https://www.eksworkshop.com/docs/fundamentals/managed-node-groups/taints/ from workshop

### EKS version

ec2-user:~/environment $ eksctl version
0.144.0

**Comment by niallthomson** [comment]
Hi @reuser , thanks for reporting this it was an issue with not passing the correct name of the branch in our CFN instructions. This has been patched in the main branch.

To fix your environment you can edit the file `~/.bashrc.d/repository.bash` in Cloud9 and change the `REPOSITORY_REF` entry to `stable`. Then restart the lab with `prepare-environment`. Please let me know if this resolves your issue.
