### ISSUE TITLE
Govcloud US-West Support?

### ISSUE THREAD

**Issue by kwilson-omitron** [aws-samples/eks-workshop-v2#648]
### What would you like to be added?

Hello,
Apologies if this is the wrong forum. I'm looking forward to working through the workshop. I only have access to an AWS account on govcloud. I have not looked at the terraform or other scripts/commands. Will I be able to work through all of the modules by just substituting the correct region, or should I expect that some aspects of the workshop won't work because features are not available in Govcloud?

Thanks for any help or advice before I begin.

### Why is this needed?

Unsure whether GovCloud is supported.

**Comment by svennam92** [comment]
GovCloud is not being tested. Please open an issue if something specific does not work in this environment.
