### ISSUE TITLE
[Bug]: Unable to inspect cluster in AWS console

### ISSUE THREAD

**Issue by reuser** [aws-samples/eks-workshop-v2#665]
### Installation method

Own AWS account

### What happened?

I'm unable to inspect EKS cluster details in the console, I'm not having rights to view objects except generic cluster information. 

### What did you expect to happen?

Access information for pods, deployments and so on through AWS console

### How can we reproduce it?

Follow workshop instructions up to https://www.eksworkshop.com/docs/observability/resource-view/workloads-view/pods_view

### EKS version

0.144

**Comment by reuser** [comment]
I fixed it by editing ConfigMap auth-aws and adding an entry:
`mapUsers: |
  - userarn: arn:aws:iam::[account_id]:root
    groups:
    - system:masters`

**Comment by ROunofF** [comment]
Hi, this is a known problem that was highlighted in this #620
