### ISSUE TITLE
[Bug]: catalog_rds_ingress sg lacks egress rule

### ISSUE THREAD

**Issue by balwa** [aws-samples/eks-workshop-v2#668]
### Installation method

Own AWS account

### What happened?

catalog_rds_ingress https://github.com/aws-samples/eks-workshop-v2/blob/bfb8dbc4263cfd598cf7e98d6b297f9f2cb40f14/manifests/modules/networking/securitygroups-for-pods/.workshop/terraform/addon_infrastructure.tf#L61
has ingress defined but no egress rule. That results in failure,

```
2023/09/10 09:47:05 Error: Unable to connect to reader database dial tcp: lookup eks-workshop-catalog.cqw3ye3epadx.us-west-2.rds.amazonaws.com: i/o timeout
2023/09/10 09:47:05 dial tcp: lookup eks-workshop-catalog.cqw3ye3epadx.us-west-2.rds.amazonaws.com: i/o timeout
```

### What did you expect to happen?

Adding egress rule 0.0.0.0/0 helps.

### How can we reproduce it?

Just create RDS instance for https://www.eksworkshop.com/docs/networking/security-groups-for-pods/ lab

### EKS version

Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.12-eks-2d98532", GitCommit:"0aa16cf4fac4da27b9e9e9ba570b990867f6a3d8", GitTreeState:"clean", BuildDate:"2023-07-28T16:52:04Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ROunofF** [comment]
Egress rule aren't needed for RDS, as they don't do outbound connections. Alternatively I didn't run into any issue running this lab. Let's us know if you still encounter this problem.
