### ISSUE TITLE
[Bug]: "/home/ec2-user/environment/eks-workshop/modules/networking/vpc-lattice/routes/checkout-route.yaml": no matches for kind "HTTPRoute" in version "gateway.networking.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by muni-annachi** [aws-samples/eks-workshop-v2#671]
### Installation method

Own AWS account

### What happened?

Running setup environment command for vpc-lattice and got below error
"/home/ec2-user/environment/eks-workshop/modules/networking/vpc-lattice/routes/checkout-route.yaml": no matches for kind "HTTPRoute" in version "gateway.networking.k8s.io/v1beta1"

### What did you expect to happen?

VPC Lattice environment should be setup successfully

### How can we reproduce it?

run **prepare-environment networking/vpc-lattice** in cloud9 terminal after setting up eks cluster with commands in setup section

### EKS version

1.25

**Comment by henriquesantanati** [comment]
Just tested [from VSCode](https://us-west-2.console.aws.amazon.com/cloudformation/home#/stacks/quickcreate?templateUrl=https://ws-assets-prod-iad-r-pdx-f3b3f9f1a7d6a3d0.s3.us-west-2.amazonaws.com/39146514-f6d5-41cb-86ef-359f9d2f7265/eks-workshop-vscode-cfn.yaml&stackName=eks-workshop-ide&param_RepositoryRef=stable) and it worked as expected:

```
$ prepare-environment networking/vpc-lattice
Refreshing copy of workshop repository from GitHub...

Resetting the environment...
Tip: Read the rest of the lab introduction while you wait!
Waiting for application to become ready...
Cleaning up previous lab infrastructure...
Creating infrastructure for next lab...
Environment is ready
```

Tested also with Cloud9 and it also worked:

```
$ prepare-environment networking/vpc-lattice
Refreshing copy of workshop repository from GitHub...

Resetting the environment...
Tip: Read the rest of the lab introduction while you wait!
Waiting for application to become ready...
Cleaning up previous lab infrastructure...
Creating infrastructure for next lab...
Environment is ready
```

@muni-annachi @irshadc , could you please confirm that it is working for you?

**Comment by svennam92** [comment]
stale issue/looks to be resolved. please comment if this changes.
