### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fingolfint** [aws-samples/eks-workshop-v2#673]
### Installation method

Own AWS account

### What happened?

When running https://www.eksworkshop.com/docs/fundamentals/fargate/scheduling running the "Apply the kustomization to the cluster:" step results in the pod not coming up with the following error:
Events:
  Type     Reason           Age   From               Message
  ----     ------           ----  ----               -------
  Warning  LoggingDisabled  93s   fargate-scheduler  Disabled logging because aws-logging configmap was not found. configmap "aws-logging" not found
  Normal   Scheduled        43s   fargate-scheduler  Successfully assigned checkout/checkout-66f6d94d79-6rhs5 to fargate-ip-10-42-162-101.us-west-2.compute.internal
  Normal   Pulling          41s   kubelet            Pulling image "public.ecr.aws/aws-containers/retail-store-sample-checkout:0.4.0"
  Warning  Failed           11s   kubelet            Failed to pull image "public.ecr.aws/aws-containers/retail-store-sample-checkout:0.4.0": rpc error: code = Unknown desc = failed to pull and unpack image "public.ecr.aws/aws-containers/retail-store-sample-checkout:0.4.0": failed to resolve reference "public.ecr.aws/aws-containers/retail-store-sample-checkout:0.4.0": failed to do request: Head "https://public.ecr.aws/v2/aws-containers/retail-store-sample-checkout/manifests/0.4.0": dial tcp 99.83.145.10:443: i/o timeout
  Warning  Failed           11s   kubelet            Error: ErrImagePull
  Normal   BackOff          11s   kubelet            Back-off pulling image "public.ecr.aws/aws-containers/retail-store-sample-checkout:0.4.0"
  Warning  Failed           11s   kubelet            Error: ImagePullBackOff

### What did you expect to happen?

Strange because applying the deplyment without the fargate Kustomization works fine:
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  74s   default-scheduler  Successfully assigned checkout/checkout-7b979686fb-7gs5j to ip-10-42-109-143.us-west-2.compute.internal
  Normal  Pulled     74s   kubelet            Container image "public.ecr.aws/aws-containers/retail-store-sample-checkout:0.4.0" already present on machine
  Normal  Created    74s   kubelet            Created container checkout
  Normal  Started    74s   kubelet            Started container checkout

### How can we reproduce it?

run the steps in https://www.eksworkshop.com/docs/fundamentals/fargate/scheduling

### EKS version

Kubernetes version
Info
1.25

**Comment by ROunofF** [comment]
Unable to reproduce. Looks like your cluster lost access to internet or there was a transient error on public ECR?
