### ISSUE TITLE
[Bug]:  prepare-environment automation/controlplanes/ack is not working

### ISSUE THREAD

**Issue by mostafafarzaneh** [aws-samples/eks-workshop-v2#704]
### Installation method

Own AWS account

### What happened?

When executing  `prepare-environment automation/controlplanes/ack`, I get the following:

```
╷
│ Error: could not download chart: unexpected status from HEAD request to https://public.ecr.aws/v2/aws-controllers-k8s/ec2-chart/manifests/v0.1.1: 403 Forbidden
│ 
│   with module.ec2.helm_release.addon[0],
│   on .terraform/modules/ec2/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 
╵
╷
│ Error: could not download chart: unexpected status from HEAD request to https://public.ecr.aws/v2/aws-controllers-k8s/rds-chart/manifests/v0.1.1: 403 Forbidden
│ 
│   with module.rds.helm_release.addon[0],
│   on .terraform/modules/rds/modules/kubernetes-addons/helm-addon/main.tf line 1, in resource "helm_release" "addon":
│    1: resource "helm_release" "addon" {
│ 

```

### What did you expect to happen?

It should be run without any error just like other module's prepare command

### How can we reproduce it?

Just run it

### Anything else we need to know?

I also had logged in to public ECR, but noting changed

### EKS version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:26:51Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.12-eks-2d98532", GitCommit:"0aa16cf4fac4da27b9e9e9ba570b990867f6a3d8", GitTreeState:"clean", BuildDate:"2023-07-28T16:52:04Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mostafafarzaneh** [comment]
I executed these commands([source](https://github.com/aws/karpenter/issues/3441)). Now it runs without any errors:
`docker logout`
`helm registry logout public.ecr.aws`

**Comment by niallthomson** [comment]
Hi @mostafafarzaneh thanks for bringing this up. I think we'll need to add explicit ECR Public authentication in our helm charts to mitigate this and make it less dependent on the underlying system.
