### ISSUE TITLE
[Bug]: Hard-coded timeout in hack/lib/run-test.sh is too short for some scenarios

### ISSUE THREAD

**Issue by arvind-v** [aws-samples/eks-workshop-v2#710]
### Installation method

Own AWS account

### What happened?

Timeout when running ```make test module="observability/opensearch"```  because the ```prepare-environment``` step that includes provisioning an OpenSearch domain takes over 120 seconds (20 minutes).  Error message below: 

```
  1) EKS Workshop
       Unknown
         Observability with OpenSearch
           Observability with OpenSearch:
     Error: Timeout of 1200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

```

Note that I already bumped up the timeout within the markdown file to 3600 seconds , but the timeout from the testing framework seems to have taken precedence. 
``` 
```bash timeout=3600 wait=30
$ prepare-environment observability/opensearch
```

Issue seems to be with hack/lib/run-test.sh where timeout value of 1200 seconds is hard-coded.
```
echo "Running test suite..."

$CONTAINER_CLI run $background_args \
  -v $SCRIPT_DIR/../website/docs:/content \
  -v $SCRIPT_DIR/../manifests:/manifests \
  -e 'EKS_CLUSTER_NAME' -e 'AWS_REGION' \
  $aws_credential_args $container_image -g "{$module,$module/**}" --hook-timeout 1200 --timeout 1200 ${AWS_EKS_WORKSHOP_TEST_FLAGS}

```

### What did you expect to happen?

Test scenario run without timeout.

### How can we reproduce it?

Run ```make test``` with a test case that takes over 20 minutes to complete 

### EKS version

1.25

**Comment by niallthomson** [comment]
Hey @arvind-v the `timeout` on the script block should always take precedence over the default that is set at the command line, at least thats how it was designed. I'll need to look in to whether there was some sort of regression.

**Comment by svennam92** [comment]
@niallthomson I believe this has been addressed with our reinvent changes. Closing for now.
