### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by karobar** [aws-samples/eks-workshop-v2#757]
### Installation method

Own AWS account

### What happened?

If i run this recommended command in my Cloud9 instance I get this output:

```
$ delete-environment
Refreshing copy of workshop repository from GitHub...

Resetting the environment, please wait
error: unknown flag: --prune-allowlist
See 'kubectl apply --help' for usage.
```

### What did you expect to happen?

I expected to be able to delete my environment.

### How can we reproduce it?

I was making my way through the lab and got to the Fundamentals->Managed Node Groups->Upgrading AMIs and then did:

`$ aws eks update-nodegroup-version --cluster-name $EKS_CLUSTER_NAME --nodegroup-name $EKS_DEFAULT_MNG_NAME`

But did a Ctrl+C because I wasn't that interested in seeing it finish

### EKS version

I don't know what this means but here's what happens if I run `aws --version`:

`aws-cli/2.13.34 Python/3.11.6 Linux/6.1.59-84.139.amzn2023.x86_64 exec-env/CloudShell exe/x86_64.amzn.2 prompt/off`

**Comment by niallthomson** [comment]
@karobar we just released an update, there should be a header at the top of the content that links to this notice:

https://www.eksworkshop.com/docs/misc/major-upgrade
