### ISSUE TITLE
EKS Pod Identity lab

### ISSUE THREAD

**Issue by niallthomson** [aws-samples/eks-workshop-v2#764]
### Outline the high level topic of the lab

https://aws.amazon.com/blogs/aws/amazon-eks-pod-identity-simplifies-iam-permissions-for-applications-on-amazon-eks-clusters/

### Provide the flow of the lab exercise, including what sample application components will be used

This lab can use the same basic flow as the IRSA lab.

### What additional AWS infrastructure or EKS addons/components will need to be created or installed to support this lab?

Pod identity addon

### What additional software or configuration will be required in the Cloud9 IDE?

None

### Are enhancements to the retail sample application required to support this lab exercise?

Yes, the SDKs for the sample application will need to be updated for pod identity support.

**Comment by hemanth-avs** [comment]
I am collaborating with @niallthomson @rodrigobersa and @ashoksrirama on adding this feature. We are extending our work on the blog to the workshop sample catalog application and working on adding the following features
- Example to demonstrate the EKS Pod Identity and Session Tags support
