### ISSUE TITLE
[feat] - Add AWS EKS Simplified Access Management Controls API  Feature to the  workshop labs

### ISSUE THREAD

**Issue by seifrajhi** [aws-samples/eks-workshop-v2#779]
### What would you like to be added?

I would like to request the addition of a new lab or section covering the recently introduced Amazon EKS simplified access management controls API. This feature enables admins to define access management configurations using familiar infrastructure as code (IaC) tools. It also allows the complete removal or refinement of permissions automatically granted to the AWS IAM principal used to create the cluster.

The lab or section should provide practical guidance and examples on how to use this new API to manage access to Amazon EKS clusters.

Details: https://aws.amazon.com/blogs/containers/a-deep-dive-into-simplified-amazon-eks-access-management-controls

### Why is this needed?

This feature streamlines IAM principal permissions during cluster creation, enhancing security and easing recovery from misconfigurations. Labs for this API would benefit users in adopting advanced access management in Amazon EKS, and keep up-to-date with AWS EKS evolution and enhancements

**Comment by niallthomson** [comment]
Resolved by #919
