### ISSUE TITLE
update: Update EFS lab to install addon in content

### ISSUE THREAD

**Issue by niallthomson** [aws-samples/eks-workshop-v2#791]
### What would you like to be added?

Update the EFS lab to install the EFS CSI driver addon using the AWS CLI instead of doing it in Terraform. The EBS lab has already been updated, see:

https://github.com/aws-samples/eks-workshop-v2/blob/main/website/docs/fundamentals/storage/ebs/ebs-csi-driver.md

And:

https://github.com/aws-samples/eks-workshop-v2/blob/main/manifests/modules/fundamentals/storage/ebs/.workshop/cleanup.sh#L5

Any IAM roles etc. required by the addon should still be created in Terraform.

### Why is this needed?

This better illustrates how EKS addons make it easy to install components like the EFS CSI driver.

**Comment by heinrichse** [comment]
Acknowledging this enhancement. I will take ownership.

**Comment by niallthomson** [comment]
This is resolved with the latest published version
