### ISSUE TITLE
new: Autoscaling with KEDA

### ISSUE THREAD

**Issue by niallthomson** [aws-samples/eks-workshop-v2#794]
### Outline the high level topic of the lab

KEDA provides a way to autoscale Kubernetes pods with a more diverse set of metrics sources than HPA alone. For example KEDA can integrate with CloudWatch and Prometheus.

### Provide the flow of the lab exercise, including what sample application components will be used

User will install KEDA in the cluster using the helm chart.

Configure a ScaledObject resource that targets the `ui` Deployment. It should use the CloudWatch scaler as a trigger and use the `RequestCountPerTarget` metrics to ensure each target only receives a specific number of HTTP requests per time period (seconds, minutes).

### What additional AWS infrastructure or EKS addons/components will need to be created or installed to support this lab?

IAM role for KEDA to access CloudWatch metrics.

AWS Load Balancer controller should be installed and an ALB via Ingress

### What additional software or configuration will be required in the Cloud9 IDE?

None

### Are enhancements to the retail sample application required to support this lab exercise?

No

**Comment by dms486** [comment]
I'll work on this
