### ISSUE TITLE
[Bug]: MinerGate closing down

### ISSUE THREAD

**Issue by simon-v-swyftx** [aws-samples/eks-workshop-v2#798]
### Installation method

Workshop Studio

### What happened?

On https://www.eksworkshop.com/docs/security/guardduty/runtime-monitoring/crypto-runtime it appears that minegate is just about to shutdown.

>Dear clients, our service is closed.
Please contact [support@minergate.com](mailto:support@minergate.com) for a refund before December 1, 2023.
All your requests will be completed by February 1, 2024
Thank you for being with us all this time.

So therefore you won't get `Execution:Runtime/NewBinaryExecuted` finding from GuardDuty

### What did you expect to happen?

Not receive a 504 from the curl command in the container

### How can we reproduce it?

Follow the docs at https://www.eksworkshop.com/docs/security/guardduty/runtime-monitoring/crypto-runtime

### EKS version

1.27

**Comment by niallthomson** [comment]
@rodrigobersa can you take a look?
