### ISSUE TITLE
[Bug]: Unable to deploy Crossplane infrastructure

### ISSUE THREAD

**Issue by JarodOliver** [aws-samples/eks-workshop-v2#819]
### Installation method

Own AWS account

### What happened?

In the Automation section, when running `prepare-environment automation/controlplanes/crossplane` the following error is thrown:

> Creating infrastructure for next lab...
> │ Error: Unsupported attribute
> │ 
> │   on .terraform/modules/eks_blueprints_addons/main.tf line 3688, in locals:
> │ 3688:   wait_for_cert_manager = var.cert_manager.wait ? [module.cert_manager] : []
> │     ├────────────────
> │     │ var.cert_manager is object with no attributes
> │ 
> │ This object does not have an attribute named "wait".

### What did you expect to happen?

I expected `prepare-environment automation/controlplanes/crossplane` to complete successfully and deploy the required infrastructure for the Crossplane lab.

### How can we reproduce it?

Run `prepare-environment automation/controlplanes/crossplane`

### EKS version

1.27.9

**Comment by niallthomson** [comment]
This seems to have been fixed by the blueprints team. Raised #822 to fix this going forwards.
