### ISSUE TITLE
Update FSx for NetApp ONTAP lab to install CSI driver Marketplace add-on in content

### ISSUE THREAD

**Issue by heinrichse** [aws-samples/eks-workshop-v2#824]
### What would you like to be added?

What would you like to be added?

Update the FSx for NetApp ONTAP lab to install the FSxN CSI driver Marketplace add-on using the AWS CLI instead of doing it in Terraform. The EBS lab has already been updated, see:

https://github.com/aws-samples/eks-workshop-v2/blob/main/website/docs/fundamentals/storage/ebs/ebs-csi-driver.md

And:

https://github.com/aws-samples/eks-workshop-v2/blob/main/manifests/modules/fundamentals/storage/ebs/.workshop/cleanup.sh#L5

Any IAM roles etc. required by the addon should still be created in Terraform.

### Why is this needed?

This better illustrates how EKS add-ons through Marketplace make it easy to install components like the FSx for NetApp ONTAP CSI driver.

**Comment by niallthomson** [comment]
Fixed in latest release
