### ISSUE TITLE
Using current stable version from setup/your-account/ produces and error for 1.29. 

### ISSUE THREAD

**Issue by isaacweathers** [aws-samples/eks-workshop-v2#832]
https://github.com/aws-samples/eks-workshop-v2/blob/078a8ca840b099947091a655cb1db74b29829d68/cluster/eksctl/cluster.yaml#L10

Using the current setup throws an Invalid version error:

`foobar:~/environment $ curl -fsSL https://raw.githubusercontent.com/aws-samples/eks-workshop-v2/stable/cluster/eksctl/cluster.yaml | envsubst | eksctl create cluster -f -
Error: invalid version, supported values: 1.23, 1.24, 1.25, 1.26, 1.27, 1.28`

Looks like it was temp disabled in us-west-2. Looking at the console it shows that 1.27 cannot be upgraded to 1.29 due to VERSION.DESC.1.29

But trying to create a new cluster from the console shows 1.29 available. Looks like the install for the Cloud9 does not have the latest version of eksctl so it comes with 0.164,0 instead of the latest 0.172.0. To fix locally you can just upgrade. 

upgrade eksctl cli
To upgrade the eksctl CLI, follow these steps:

Open your terminal and run the following command to update the eksctl package:
`curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp`

Move the updated binary to the appropriate directory. You may need to adjust the path based on your system:
`sudo mv /tmp/eksctl /usr/local/bin`

Verify the version has been upgraded by running:
`eksctl version`

The output should show the latest version of eksctl, confirming the upgrade was successful.

If I get time will put in a PR for the Cloud9 install.

**Comment by niallthomson** [comment]
This is resolved with the latest published version
