### ISSUE TITLE
[Bug]: wget command returns empty file

### ISSUE THREAD

**Issue by robertocamp** [aws-samples/eks-workshop-v2#842]
### Installation method

Own AWS account

### What happened?

Per lab instructions:

- `wget -q https://raw.githubusercontent.com/aws-samples/eks-workshop-v2/pull/831/head/lab/cfn/eks-workshop-ide-cfn.yaml -O eks-workshop-ide-cfn.yaml`
- executing this command returns an empty file

### What did you expect to happen?

Expecting to receive a working eks-workshop-ide-cfn.yaml file

### How can we reproduce it?

1. Navigate to: https://www.eksworkshop.com/docs/introduction/setup/your-account/
2. start CloudShell (use the link)
3. copy command instructions:  `wget -q https://raw.githubusercontent.com/aws-samples/eks-workshop-v2/pull/831/head/lab/cfn/eks-workshop-ide-cfn.yaml -O eks-workshop-ide-cfn.yaml`
4. run command in CloudShell
5. `cat eks-workshop-ide-cfn.yaml` returns empty file

### EKS version

N/A

**Comment by jan-ludvik** [comment]
I had the same problem and found it just now. It is referring to a PR.
You can change that link to
`https://raw.githubusercontent.com/aws-samples/eks-workshop-v2/main/lab/cfn/eks-workshop-ide-cfn.yaml`

**Comment by niallthomson** [comment]
Hi folks. We've had some issues with Netlify caching content from different branches across builds that has caused an issue in the past. Checking the content right now it appears to show the correct branch. I'll leave this open for tracking.

**Comment by niallthomson** [comment]
I believe this has been resolved by a change to the netlify deploy script that clears the build cache. Closing this for now and will re-open if this occurs again.
