### ISSUE TITLE
Add a Mountpoint for Amazon S3 Module to the Fundamentals/Storage exercises

### ISSUE THREAD

**Issue by heinrichse** [aws-samples/eks-workshop-v2#843]
### Outline the high level topic of the lab

This module will walk the user through the process of installing the CSI driver for Mountpoint for Amazon S3 and then using the CSI driver to provision storage on S3 using Mountpoint for file level access in EKS. 

### Provide the flow of the lab exercise, including what sample application components will be used

-     IAM roles for CSI driver created in Terraform
-     S3 bucket created in Terraform
-     CSI Driver installed manually from the repo of the CSI driver
-     Storage Class deployed manually 
-     PVC created manually 
-     Deploy an nginx pod using a deployment and add a new product sku in S3 via Mountpoint
-     Clean up the environment using Terraform

### What additional AWS infrastructure or EKS addons/components will need to be created or installed to support this lab?

- S3 bucket
- IAM role for CSI driver

### What additional software or configuration will be required in the Cloud9 IDE?

None

### Are enhancements to the retail sample application required to support this lab exercise?

TBD

**Comment by pengc99** [comment]
hi; i'll take this issue

**Comment by ss-aws** [comment]
pls add

**Comment by rchandra20** [comment]
Could I please be assigned to this issue?
