### ISSUE TITLE
[Bug]: bash: line 160: EKS_DEFAULT_MNG_MIN: unbound variable

### ISSUE THREAD

**Issue by cemendes** [aws-samples/eks-workshop-v2#852]
### Installation method

Own AWS account

### What happened?

Running the Load Balancers lab, and getting this error when running 'prepare-environment exposing/load-balancer'

prepare-environment exposing/load-balancer
Refreshing copy of workshop repository from GitHub...

Resetting the environment...
Tip: Read the rest of the lab introduction while you wait!
Waiting for application to become ready...
Cleaning up previous lab infrastructure...
Creating infrastructure for next lab...
An error occurred, please contact your workshop proctor or raise an issue at https://github.com/aws-samples/eks-workshop-v2/issues
bash: line 160: EKS_DEFAULT_MNG_MIN: unbound variable
The full log can be found here: /eks-workshop/logs/action-1710462592.log

### What did you expect to happen?

The script to finish without issues. 

### How can we reproduce it?

Run 'prepare-environment exposing/load-balancer' in cloud 9

### Anything else we need to know?

Output of the /eks-workshop/logs/action-1710463618.log

Plan: 5 to add, 0 to change, 0 to destroy.
module.eks_blueprints_addons.module.aws_load_balancer_controller.aws_iam_role.this[0]: Creating...
module.eks_blueprints_addons.time_sleep.this: Creating...
module.eks_blueprints_addons.module.aws_load_balancer_controller.aws_iam_policy.this[0]: Creating...
module.eks_blueprints_addons.module.aws_load_balancer_controller.aws_iam_policy.this[0]: Creation complete after 1s [id=arn:aws:iam::986566589085:policy/alb-controller-20240315004837100300000002]
module.eks_blueprints_addons.module.aws_load_balancer_controller.aws_iam_role.this[0]: Creation complete after 1s [id=alb-controller-20240315004837092500000001]
module.eks_blueprints_addons.module.aws_load_balancer_controller.aws_iam_role_policy_attachment.this[0]: Creating...
module.eks_blueprints_addons.module.aws_load_balancer_controller.aws_iam_role_policy_attachment.this[0]: Creation complete after 0s [id=alb-controller-20240315004837092500000001-20240315004837832200000003]
module.eks_blueprints_addons.time_sleep.this: Still creating... [10s elapsed]
module.eks_blueprints_addons.time_sleep.this: Still creating... [20s elapsed]
module.eks_blueprints_addons.time_sleep.this: Still creating... [30s elapsed]
module.eks_blueprints_addons.time_sleep.this: Creation complete after 30s [id=2024-03-15T00:49:07Z]
module.eks_blueprints_addons.module.aws_load_balancer_controller.helm_release.this[0]: Creating...
module.eks_blueprints_addons.module.aws_load_balancer_controller.helm_release.this[0]: Creation complete after 4s [id=aws-load-balancer-controller]

Apply complete! Resources: 5 added, 0 changed, 0 destroyed.

### EKS version

1.29

**Comment by niallthomson** [comment]
Hey @cemendes this usually happens if you haven't use `use-cluster eks-workshop` before starting the labs. Was this the first lab you ran?

**Comment by cemendes** [comment]
Yes, it was the very first lab. Can you show me in the docs where it says to use the `use-cluster eks workshop`. I don't see them in https://www.eksworkshop.com/docs/introduction/getting-started/first

**Comment by niallthomson** [comment]
Its on the pages for eksctl and Terraform after the cluster is provisioned.

**Comment by niallthomson** [comment]
I've pushed an update that will provide a better error message with specific instructions.
