### ISSUE TITLE
[Bug]: Terraform instructions do not set environment variable EKS_CLUSTER_NAME

### ISSUE THREAD

**Issue by friedmsf** [aws-samples/eks-workshop-v2#887]
### Installation method

Own AWS account

### What happened?

While following the instructions to deploy in my own environment with Terraform, Step 2 "un the following commands to deploy the workshop environment" fails to deploy due to errors with var.cluster_name.  If you set the environment variable, EKS_CLUSTER_NAME, and then run the command it works fine.

### What did you expect to happen?

Terraform to deploy without error

### How can we reproduce it?

Download the terraform files and run the following per the instructions:
terraform init
terraform apply -var="cluster_name=$EKS_CLUSTER_NAME" -auto-approve

### EKS version

any

**Comment by niallthomson** [comment]
Fixed by #795
