### ISSUE TITLE
[Bug]: $EKS_CLUSTER_NAME is not defined

### ISSUE THREAD

**Issue by shankey28** [aws-samples/eks-workshop-v2#912]
### Installation method

Own AWS account

### What happened?

got an error running below command:

terraform apply -var="cluster_name=$EKS_CLUSTER_NAME" -auto-approve

Error message:

"name" doesn't comply with restrictions ("^[0-9A-Za-z][0-9A-Za-z_-]*$"): ""
cluster_name

### What did you expect to happen?

terraform apply to happen 

### How can we reproduce it?

follow the lab steps in own aws account

### EKS version

following the workshop files

**Comment by niallthomson** [comment]
Fixed by #795
