### ISSUE TITLE
[Bug]: An error occurred (ResourceNotFoundException) when calling the DescribeNodegroup operation: No node group found for name: default-20240424100336089600000010.

### ISSUE THREAD

**Issue by shankey28** [aws-samples/eks-workshop-v2#915]
### Installation method

Own AWS account

### What happened?

Got error when executed below command:

prepare-environment fundamentals/storage/ebs

Error:

An error occurred (ResourceNotFoundException) when calling the DescribeNodegroup operation: No node group found for name: default-20240424100336089600000010.
An error occurred, please contact your workshop proctor or raise an issue at https://github.com/aws-samples/eks-workshop-v2/issues
The full log can be found here: /eks-workshop/logs/action-1714463707.log

### What did you expect to happen?

Expected for command to be successful

### How can we reproduce it?

I updated and executed eks.tf

  eks_managed_node_groups = {
    default = {
      instance_types       = ["t2.large"]
      force_update_version = true
      release_version      = var.ami_release_version
      
            block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = 75
            delete_on_termination = true
          }
        }
      }

### EKS version

1.29

**Comment by shankey28** [comment]
Upon further investigation, looks like the command uses old values from env.bash file

**Comment by niallthomson** [comment]
So does it appear that you updated the node group in the Terraform, re-ran `apply` and the node group name changed?

**Comment by niallthomson** [comment]
I'm going to close this issue since we've migrated the Terraform to use a static node group name
