### ISSUE TITLE
[Bug]: Cloud9 eks workshop setup failure

### ISSUE THREAD

**Issue by cskalyan** [aws-samples/eks-workshop-v2#931]
### Installation method

Own AWS account

### What happened?

I am unable to setup Cloud9 Environment in my AWS Account and I keep getting this error
Failed to create/update the stack. Run the following command
to fetch the list of events leading up to the failure
aws cloudformation describe-stack-events --stack-name eks-workshop-ide

### What did you expect to happen?

Successful stack creation.

### How can we reproduce it?

Run below in US-EAST-1

wget -q https://raw.githubusercontent.com/aws-samples/eks-workshop-v2/stable/lab/cfn/eks-workshop-ide-cfn.yaml -O eks-workshop-ide-cfn.yaml
aws cloudformation deploy --stack-name eks-workshop-ide \
    --template-file ./eks-workshop-ide-cfn.yaml \
    --parameter-overrides RepositoryRef=stable \
    --capabilities CAPABILITY_NAMED_IAM

### EKS version

1.29

**Comment by princeanire** [comment]
Have you check if you have a default VPC in us-east-1?

**Comment by princeanire** [comment]
It seems that the Cloud9 IDE is deployed in the default VPC

**Comment by cskalyan** [comment]
> Have you check if you have a default VPC in us-east-1?

I do have default VPC in US-EAST-1 and it has 6 subnets.

**Comment by princeanire** [comment]
have you tried checking the root cuase via aws cloudformation template?

I think there would an error that will be displayed on the consoke,
that might help troubleshooting the setup failure

**Comment by cskalyan** [comment]
I did check on AWS Console and all I see is EksWorkshopC9Instance create failed. When I monitor in detail, I see that it is saying connecting but connecting to EC2 is failing.

**Comment by niallthomson** [comment]
Hi folks,

Currently the CloudFormation template assumes either:

1. You deploy to the default VPC (default behavior)
2. You use the `CloudSubnet` [parameter](https://github.com/aws-samples/eks-workshop-v2/blob/main/lab/cfn/eks-workshop-ide-cfn.yaml#L47) to specify an alternative VPC

I think something we might want to do in the future is always create a dedicated VPC but we don't do that at the moment.

**Comment by cskalyan** [comment]
It did not help. I tried defining VPC-ID and also Subnet id.

Looks like SSH connection to the instance is failing. All I see is
connecting status and nothing happens.

**Comment by niallthomson** [comment]
Does your default VPC have Internet access?

**Comment by Obasoro** [comment]
Experiencing the same thing ```Failed to create/update the stack```. I created the stack in us-west-2 and the still did not work.

**Comment by niallthomson** [comment]
Closing this as Cloud9 is no longer presented as an option
