### ISSUE TITLE
[Bug]: Fundamentals - Storage - FSx For NetApp ONTAP - Addon version specified is not supported

### ISSUE THREAD

**Issue by henriquesantanati** [aws-samples/eks-workshop-v2#964]
### Installation method

Own AWS account

### What happened?

While running `prepare-environment fundamentals/storage/fsxn`, I've received the following error message after a while:

```
╷
│ Error: creating EKS Add-On (eks-workshop:netapp_trident-operator): operation error EKS: CreateAddon, https response error StatusCode: 400, RequestID: 9973b068-8305-467e-bf0e-8683d13a8501, InvalidParameterException: Addon version specified is not supported
│ 
│   with module.lab.aws_eks_addon.fsxn_csi_addon,
│   on lab/main.tf line 1, in resource "aws_eks_addon" "fsxn_csi_addon":
│    1: resource "aws_eks_addon" "fsxn_csi_addon" {
```

### What did you expect to happen?

Expected that it would prepare the lab environment successfuly

### How can we reproduce it?

Run the `prepare-environment fundamentals/storage/fsxn` command

### Anything else we need to know?

I was using Workshop Studio envornment.

### EKS version

1.29
EKS Workshop build URL: build-9886a22.eksworkshop.com

**Comment by niallthomson** [comment]
Thanks for reporting, I'm taking a look at various fixes for this lab

**Comment by niallthomson** [comment]
This lab is being removed for now until issues are resolved.
